import os
import sys

seed_content = '''import bcrypt from 'bcryptjs';
import {
  User,
  PatientProfile,
  DoctorProfile,
  Clinic,
  ClinicDoctor,
  Laboratory,
  DiagnosticTest,
  Appointment,
  Queue,
  QueueTicket,
  Referral,
  TestBooking,
  Sample,
  MedicalReport,
  Review,
  Notification,
  AuditLog
} from '../types/index.js';

export function getInitialSeedData() {
  const now = new Date().toISOString();
  const todayStr = now.split('T')[0];

  const salt = bcrypt.genSaltSync(10);
  const passwordPatient = bcrypt.hashSync('Patient@123', salt);
  const passwordDoctor = bcrypt.hashSync('Doctor@123', salt);
  const passwordClinic = bcrypt.hashSync('Clinic@123', salt);
  const passwordLab = bcrypt.hashSync('Lab@123', salt);
  const passwordAdmin = bcrypt.hashSync('Admin@123', salt);

  const users: User[] = [
    {
      id: 'usr-admin-1',
      email: 'admin@medilink.com',
      passwordHash: passwordAdmin,
      name: 'MediLink Lucknow Admin',
      role: 'ADMIN',
      phone: '+91 522 220 9001',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-pat-1',
      email: 'patient@medilink.com',
      passwordHash: passwordPatient,
      name: 'Rahul Sharma',
      role: 'PATIENT',
      phone: '+91 98765 43210',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-1',
      email: 'doctor@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Ananya Srivastava, MD, DM',
      role: 'DOCTOR',
      phone: '+91 94150 12890',
      avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-2',
      email: 'rajeshwar.verma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rajeshwar Verma, MS, MCh',
      role: 'DOCTOR',
      phone: '+91 98390 44521',
      avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-3',
      email: 'priya.mehrotra@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Priya Mehrotra, MD (Endo)',
      role: 'DOCTOR',
      phone: '+91 97210 88200',
      avatarUrl: 'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-4',
      email: 'manish.verma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Manish Verma, MD, DM',
      role: 'DOCTOR',
      phone: '+91 94150 33410',
      avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-5',
      email: 'sunita.chandra@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Sunita Chandra, MS, FICOG',
      role: 'DOCTOR',
      phone: '+91 98391 77620',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-6',
      email: 'rishi.sethi@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rishi Sethi, MD, DM (Cardio)',
      role: 'DOCTOR',
      phone: '+91 94500 88120',
      avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-7',
      email: 'sandeep.kapoor@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Sandeep Kapoor, MS (Ortho)',
      role: 'DOCTOR',
      phone: '+91 98390 11990',
      avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-8',
      email: 'rashmi.kumar@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rashmi Kumar, MD, FAMS',
      role: 'DOCTOR',
      phone: '+91 94150 99400',
      avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-9',
      email: 'rakesh.tandon@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rakesh Tandon, MD, DM (Gastro)',
      role: 'DOCTOR',
      phone: '+91 97210 55110',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-10',
      email: 'neha.rastogi@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Neha Rastogi, MD (Derm)',
      role: 'DOCTOR',
      phone: '+91 98392 44330',
      avatarUrl: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-11',
      email: 'ajay.verma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Ajay Verma, MD, DNB (Pulmo)',
      role: 'DOCTOR',
      phone: '+91 94151 22880',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-12',
      email: 'amit.agarwal@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Amit Agarwal, MS (ENT)',
      role: 'DOCTOR',
      phone: '+91 98390 66770',
      avatarUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-clinic-1',
      email: 'clinic@medilink.com',
      passwordHash: passwordClinic,
      name: 'Awadh Mediplex & Heart Institute',
      role: 'CLINIC',
      phone: '+91 522 409 1200',
      avatarUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-lab-1',
      email: 'lab@medilink.com',
      passwordHash: passwordLab,
      name: 'Dr. Lal PathLabs National Reference Hub',
      role: 'LABORATORY',
      phone: '+91 522 409 8899',
      avatarUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const patientProfiles: PatientProfile[] = [
    {
      id: 'pat-prof-1',
      userId: 'usr-pat-1',
      dateOfBirth: '1989-05-14',
      gender: 'MALE',
      bloodGroup: 'B_POSITIVE',
      address: 'B-4/112, Sector 4, Gomti Nagar, Lucknow',
      city: 'Lucknow',
      emergencyContact: '+91 98765 11223',
      allergiesJson: JSON.stringify(['Penicillin (Mild urticaria)', 'Sulfa drugs']),
      chronicConditionsJson: JSON.stringify(['Primary Hypertension (Grade 1)', 'Mild Hyperuricemia']),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinics: Clinic[] = [
    {
      id: 'cln-1',
      userId: 'usr-clinic-1',
      name: 'Awadh Mediplex & Heart Institute',
      address: 'TCG 4/4, Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      phone: '+91 522 409 1200',
      email: 'admin@awadhmediplex.com',
      registrationNo: 'UP-LKO-CLINIC-2022-901',
      servicesJson: JSON.stringify(['Interventional Cardiology', 'Digital ECG & 2D Echo', 'Diabetic Care Unit', 'Executive Health Checkups', 'In-house Pharmacy']),
      facilitiesJson: JSON.stringify(['Wheelchair Accessible', 'Emergency Triage', 'NABL Blood Draw Lounge', 'Covered Parking', 'Live Token Screens']),
      openingTime: '08:00',
      closingTime: '21:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 312,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-2',
      userId: 'usr-clinic-1',
      name: 'Hazratganj Specialty Polyclinic & Diagnostics',
      address: '24 Ashok Marg, Near Hazratganj Crossing',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      phone: '+91 522 228 3344',
      email: 'hazratganj@polyclinic.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2021-412',
      servicesJson: JSON.stringify(['Neurology & Stroke Clinic', 'Headache & Migraine Centre', 'Dermatology & Cosmetology', 'Infertility Assessment']),
      facilitiesJson: JSON.stringify(['Central Air Conditioning', 'Neuro Rehab Suite', 'Express Lab Counter', 'Valet Parking', 'Live Queue Display']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 240,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-3',
      userId: 'usr-clinic-1',
      name: 'Kapoorthala Health & Diabetes Care Centre',
      address: 'Plot 18, Sector B, Kapoorthala, Aliganj',
      city: 'Lucknow',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8920,
      longitude: 80.9385,
      phone: '+91 522 237 9900',
      email: 'aliganj@healthcity.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2023-118',
      servicesJson: JSON.stringify(['Endocrinology & Thyroid Care', 'Continuous Glucose Monitoring (CGM)', 'Diet & Lifestyle Counseling', 'Diabetic Foot Clinic']),
      facilitiesJson: JSON.stringify(['Consultation Chambers', 'Pharmacy', 'Diagnostic Collection Point', 'Patient Education Kiosk']),
      openingTime: '08:30',
      closingTime: '19:30',
      isVerified: true,
      rating: 4.9,
      reviewCount: 195,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-4',
      userId: 'usr-clinic-1',
      name: 'Medanta Super Speciality OPD & Medical Centre',
      address: 'Sector A, Pocket 1, Amar Shaheed Path, Golf City',
      city: 'Lucknow',
      area: 'Sushant Golf City & Shaheed Path',
      latitude: 26.7935,
      longitude: 81.0112,
      phone: '+91 522 450 5050',
      email: 'opd@medanta-lucknow.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2020-008',
      servicesJson: JSON.stringify(['Comprehensive Gastroenterology', 'Cardiology OPD', 'Medical Oncology', 'Organ Transplant Follow-up']),
      facilitiesJson: JSON.stringify(['NABH Accredited Complex', 'Advanced Diagnostic Wing', 'Daycare Surgery', 'Ample Basement Parking']),
      openingTime: '08:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 420,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-5',
      userId: 'usr-clinic-1',
      name: 'Apollo Clinic & Joint Care Centre',
      address: 'Sector B, Bargawan, Kanpur Road (Near Phoenix United)',
      city: 'Lucknow',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7885,
      longitude: 80.8920,
      phone: '+91 522 667 7788',
      email: 'alambagh@apolloclinic.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2021-789',
      servicesJson: JSON.stringify(['Orthopaedics & Joint Replacement', 'Sports Injury Clinic', 'Physiotherapy & Ergonomics', 'Diagnostic X-Ray']),
      facilitiesJson: JSON.stringify(['Apollo Standard Hygiene', 'Digital Radiology', 'Physio Gymnasium', 'Direct Lab Counter']),
      openingTime: '08:30',
      closingTime: '20:30',
      isVerified: true,
      rating: 4.8,
      reviewCount: 215,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-6',
      userId: 'usr-clinic-1',
      name: 'Chandan Multispecialty OPD & Diagnostics',
      address: 'Faizabad Road, Near Indira Nagar Metro Station',
      city: 'Lucknow',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8830,
      longitude: 80.9910,
      phone: '+91 522 423 3300',
      email: 'indiranagar@chandan.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2019-332',
      servicesJson: JSON.stringify(['Pulmonology & Allergy Care', 'ENT & Head-Neck Clinic', 'General Medicine', 'Executive Health Checkups']),
      facilitiesJson: JSON.stringify(['NABL Accreditated Labs', 'Spirometry PFT Lab', 'Audio-Speech Therapy', 'Pharmacy']),
      openingTime: '08:00',
      closingTime: '21:00',
      isVerified: true,
      rating: 4.7,
      reviewCount: 280,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-7',
      userId: 'usr-clinic-1',
      name: 'Charak Medical Centre & Child Health',
      address: 'Dubagga Crossing, Hardoi Link Road, Chowk',
      city: 'Lucknow',
      area: 'Chowk & Old Lucknow',
      latitude: 26.8720,
      longitude: 80.8840,
      phone: '+91 522 241 1234',
      email: 'charak@medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2022-441',
      servicesJson: JSON.stringify(['Pediatrics & Child Vaccination', 'Neonatal Care', 'Cardiology & General Medicine', 'Mother & Child Care']),
      facilitiesJson: JSON.stringify(['Children Play Area', 'Vaccine Cold Chain Facility', 'Pharmacy', 'Emergency Stabilisation']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 165,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-8',
      userId: 'usr-clinic-1',
      name: 'Mahanagar Health Suites & Super Care',
      address: 'Mandir Marg, Near Gole Market, Mahanagar',
      city: 'Lucknow',
      area: 'Mahanagar & Nishatganj',
      latitude: 26.8750,
      longitude: 80.9520,
      phone: '+91 522 233 4455',
      email: 'mahanagar@medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2023-552',
      servicesJson: JSON.stringify(['Obstetrics & Gynaecology', 'Dermatology & Aesthetics', 'Pediatrics', 'Dietetics & Nutrition']),
      facilitiesJson: JSON.stringify(['Private Consultation Suites', 'Ultrasound & Fetal Monitoring', 'Dedicated Daycare', 'Wi-Fi Lounge']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 190,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const doctorProfiles: DoctorProfile[] = [
    {
      id: 'doc-prof-1',
      userId: 'usr-doc-1',
      specialty: 'Cardiology',
      subSpecialty: 'Interventional & Preventive Cardiology',
      experienceYears: 16,
      qualification: 'MBBS (KGMU Lucknow), MD (Medicine), DM (Cardiology)',
      licenseNumber: 'UPMC-54210',
      consultationFee: 800.0,
      bio: 'Senior Interventional Cardiologist in Lucknow with over 16 years of clinical excellence. Specializes in preventive cardiology, hypertension control, complex dyslipidemia management, and non-invasive cardiac evaluation.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 220,
      clinicId: 'cln-1',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-2',
      userId: 'usr-doc-2',
      specialty: 'Orthopaedics',
      subSpecialty: 'Spine, Joint Replacement & Trauma Reconstruction',
      experienceYears: 14,
      qualification: 'MBBS, MS (General Surgery), MCh (Neurosurgery & Spine)',
      licenseNumber: 'UPMC-48901',
      consultationFee: 750.0,
      bio: 'Renowned spine and reconstructive surgeon associated with Awadh Mediplex and SGPGIMS corridor. Expert in robotic knee arthroplasty, disc herniation management, and minimally invasive spine surgeries.',
      consultationDuration: 20,
      rating: 4.8,
      reviewCount: 165,
      clinicId: 'cln-1',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-3',
      userId: 'usr-doc-3',
      specialty: 'Endocrinology',
      subSpecialty: 'Type 1 & 2 Diabetes, Thyroid & Metabolic Disorders',
      experienceYears: 11,
      qualification: 'MBBS, MD (Medicine), Fellowship in Clinical Endocrinology (AIIMS)',
      licenseNumber: 'UPMC-61204',
      consultationFee: 700.0,
      bio: 'Expert endocrinologist at Aliganj, Lucknow specializing in insulin pump titration, gestational diabetes, Hashimoto thyroiditis, and obesity-linked metabolic syndrome.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 195,
      clinicId: 'cln-3',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8920,
      longitude: 80.9385,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-4',
      userId: 'usr-doc-4',
      specialty: 'Neurology',
      subSpecialty: 'Stroke, Epilepsy, Migraine & Neuropathy',
      experienceYears: 15,
      qualification: 'MBBS (KGMU), MD (Medicine), DM (Neurology)',
      licenseNumber: 'UPMC-49210',
      consultationFee: 900.0,
      bio: 'Senior consultant neurologist at Hazratganj and Chandan Hospital. Renowned for management of intractable headaches, Parkinson disease, acute ischemic stroke thrombolysis, and peripheral neuropathy.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 180,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-5',
      userId: 'usr-doc-5',
      specialty: 'Gynaecology',
      subSpecialty: 'High-Risk Pregnancy, Infertility & Laparoscopic Surgery',
      experienceYears: 18,
      qualification: 'MBBS, MS (Obs & Gynae), FICOG, Diploma in Advanced Endoscopy',
      licenseNumber: 'UPMC-38102',
      consultationFee: 800.0,
      bio: 'Eminent gynaecologist and obstetrician practicing in Hazratganj and Mahanagar. Special interest in recurrent pregnancy loss, adolescent PCOS management, painless delivery, and laparoscopic fibroid removal.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 290,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-6',
      userId: 'usr-doc-6',
      specialty: 'Cardiology',
      subSpecialty: 'Coronary Angioplasty, Pacemakers & Heart Failure',
      experienceYears: 20,
      qualification: 'MBBS, MD, DM (Cardiology), FACC (USA), FSCAI',
      licenseNumber: 'UPMC-31092',
      consultationFee: 1000.0,
      bio: 'Distinguished professor and interventional cardiologist connected with KGMU medical corridor and Charak clinic. Over 10,000 coronary angiographies and angioplasties performed with excellent clinical outcomes.',
      consultationDuration: 15,
      rating: 5.0,
      reviewCount: 340,
      clinicId: 'cln-7',
      area: 'Chowk & Old Lucknow',
      latitude: 26.8720,
      longitude: 80.8840,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-7',
      userId: 'usr-doc-7',
      specialty: 'Orthopaedics',
      subSpecialty: 'Computer-Navigated Joint Replacement & Arthroscopy',
      experienceYears: 17,
      qualification: 'MBBS, MS (Orthopaedics), MCh Ortho (UK)',
      licenseNumber: 'UPMC-44510',
      consultationFee: 800.0,
      bio: 'Chief orthopaedic surgeon at Apollo Clinic, Alambagh. Specializes in total hip and knee replacements, ligament tear reconstructions (ACL/PCL), and complex osteoporotic fracture management.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 210,
      clinicId: 'cln-5',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7885,
      longitude: 80.8920,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-8',
      userId: 'usr-doc-8',
      specialty: 'Pediatrics',
      subSpecialty: 'Pediatric Neurology, Developmental Disorders & Immunization',
      experienceYears: 22,
      qualification: 'MBBS, MD (Pediatrics), FAMS, Ex-Head of Pediatrics KGMU',
      licenseNumber: 'UPMC-26780',
      consultationFee: 700.0,
      bio: 'Celebrated pediatrician in Lucknow with more than two decades of dedicated care. Expert in developmental milestones, childhood epilepsy, respiratory infections, and comprehensive child immunization regimens.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 380,
      clinicId: 'cln-8',
      area: 'Mahanagar & Nishatganj',
      latitude: 26.8750,
      longitude: 80.9520,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-9',
      userId: 'usr-doc-9',
      specialty: 'Gastroenterology',
      subSpecialty: 'Therapeutic Endoscopy, Liver Cirrhosis & IBD',
      experienceYears: 19,
      qualification: 'MBBS, MD (Medicine), DM (Gastroenterology, AIIMS)',
      licenseNumber: 'UPMC-39820',
      consultationFee: 1000.0,
      bio: 'Senior director of digestive diseases at Medanta Super Speciality Hub Lucknow. Expertise spans fatty liver disease, GERD/acid peptic disorder, colonoscopy screenings, and inflammatory bowel disease.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 275,
      clinicId: 'cln-4',
      area: 'Sushant Golf City & Shaheed Path',
      latitude: 26.7935,
      longitude: 81.0112,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-10',
      userId: 'usr-doc-10',
      specialty: 'Dermatology',
      subSpecialty: 'Clinical Dermatology, Psoriasis, Acne & Laser Surgery',
      experienceYears: 10,
      qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
      licenseNumber: 'UPMC-63412',
      consultationFee: 650.0,
      bio: 'Leading dermatologist in Central Lucknow specializing in chronic eczema, vitiligo phototherapy, stubborn adult acne, fungal dermatoses, and anti-aging aesthetic procedures.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 160,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-11',
      userId: 'usr-doc-11',
      specialty: 'Pulmonology',
      subSpecialty: 'Asthma, COPD, Interstitial Lung Disease & Sleep Apnea',
      experienceYears: 13,
      qualification: 'MBBS, MD (Pulmonary Medicine), DNB, FCCP',
      licenseNumber: 'UPMC-52119',
      consultationFee: 700.0,
      bio: 'Consultant chest physician at Chandan Hospital, Faizabad Road. Proficient in digital bronchoscopy, allergic bronchopulmonary aspergillosis, post-COVID lung fibrosis, and sleep-disordered breathing.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 145,
      clinicId: 'cln-6',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8830,
      longitude: 80.9910,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Wednesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-12',
      userId: 'usr-doc-12',
      specialty: 'ENT',
      subSpecialty: 'Endoscopic Sinus Surgery, Micro-Ear Surgery & Vertigo',
      experienceYears: 12,
      qualification: 'MBBS, MS (Otorhinolaryngology)',
      licenseNumber: 'UPMC-57890',
      consultationFee: 600.0,
      bio: 'ENT specialist at Indira Nagar and Faizabad Road corridor. Dedicated practice in chronic sinusitis, allergic rhinitis, eardrum perforation repair (tympanoplasty), and vestibular vertigo management.',
      consultationDuration: 15,
      rating: 4.7,
      reviewCount: 130,
      clinicId: 'cln-6',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8830,
      longitude: 80.9910,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinicDoctors: ClinicDoctor[] = [
    { id: 'cln-doc-1', clinicId: 'cln-1', doctorId: 'doc-prof-1', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']), roomNo: 'Room 102 - Cardiology Wing', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-2', clinicId: 'cln-1', doctorId: 'doc-prof-2', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Room 204 - Ortho & Spine Wing', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-3', clinicId: 'cln-3', doctorId: 'doc-prof-3', daysAvailableJson: JSON.stringify(['Tuesday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Chamber 108 - Endocrine Suite', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-4', clinicId: 'cln-2', doctorId: 'doc-prof-4', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Thursday', 'Friday']), roomNo: 'Suite 201 - Neuro Sciences', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-5', clinicId: 'cln-2', doctorId: 'doc-prof-5', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Thursday', 'Saturday']), roomNo: 'Suite 104 - Women Health', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-6', clinicId: 'cln-7', doctorId: 'doc-prof-6', daysAvailableJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']), roomNo: 'Chamber 3 - Cardiac Clinic', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-7', clinicId: 'cln-5', doctorId: 'doc-prof-7', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'OPD 1 - Orthopaedics', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-8', clinicId: 'cln-8', doctorId: 'doc-prof-8', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']), roomNo: 'Suite A - Pediatrics', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-9', clinicId: 'cln-4', doctorId: 'doc-prof-9', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'OPD Block 4 - Gastroenterology', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-10', clinicId: 'cln-2', doctorId: 'doc-prof-10', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']), roomNo: 'Suite 302 - Dermatology', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-11', clinicId: 'cln-6', doctorId: 'doc-prof-11', daysAvailableJson: JSON.stringify(['Tuesday', 'Wednesday', 'Thursday', 'Saturday']), roomNo: 'Room 12 - Chest Medicine', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-12', clinicId: 'cln-6', doctorId: 'doc-prof-12', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Room 8 - ENT OPD', status: 'ACTIVE', createdAt: now }
  ];

  const laboratories: Laboratory[] = [
    {
      id: 'lab-1',
      userId: 'usr-lab-1',
      name: 'Dr. Lal PathLabs National Reference Hub',
      address: '22 Sapru Marg, Near Prem Mandir, Hazratganj',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8490,
      longitude: 80.9480,
      phone: '+91 522 409 8899',
      email: 'lucknow.reference@lalpathlabs.com',
      licenseNo: 'NABL-UP-LAL-2022-881',
      accreditation: 'NABL & CAP Accredited National Reference Lab',
      isVerified: true,
      rating: 4.9,
      reviewCount: 520,
      turnaroundTimeNote: 'Same-day 4-8 hours for all core biochemistry & hematology panels',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-2',
      userId: 'usr-lab-1',
      name: 'Thyrocare Technologies Regional Processing Lab',
      address: 'Shop 4-6, Ground Floor, Kapoorthala Shopping Complex, Aliganj',
      city: 'Lucknow',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8910,
      longitude: 80.9390,
      phone: '+91 522 237 4411',
      email: 'aliganj@thyrocare.com',
      licenseNo: 'NABL-UP-THY-2021-309',
      accreditation: 'NABL & ICMR Certified Fully Automated Track System',
      isVerified: true,
      rating: 4.8,
      reviewCount: 410,
      turnaroundTimeNote: '6-12 hours digital report with automated SMS download link',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-3',
      userId: 'usr-lab-1',
      name: 'Agilus Diagnostics (Formerly SRL Diagnostics)',
      address: 'Plot 14, Rana Pratap Marg, Near Dainik Jagran Chauraha',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8520,
      longitude: 80.9420,
      phone: '+91 522 405 6789',
      email: 'care.lucknow@agilus.in',
      licenseNo: 'NABL-UP-AGI-2020-512',
      accreditation: 'NABL Accredited & Dual International Quality Certified',
      isVerified: true,
      rating: 4.9,
      reviewCount: 390,
      turnaroundTimeNote: '6-8 hours guaranteed TAT for routine blood & viral assays',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-4',
      userId: 'usr-lab-1',
      name: 'Chandan Diagnostic Centre & Imaging Hub',
      address: '15/2, Faizabad Road, Opposite Indira Nagar Metro Station',
      city: 'Lucknow',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8835,
      longitude: 80.9920,
      phone: '+91 522 423 3333',
      email: 'diagnostics@chandan.co.in',
      licenseNo: 'NABL-UP-CHN-2019-108',
      accreditation: 'NABL, NABH & ISO 15189 Quality Certified Medical Laboratory',
      isVerified: true,
      rating: 4.8,
      reviewCount: 460,
      turnaroundTimeNote: '4-8 hours for pathology panels; 12 hours for specialized hormonal assays',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-5',
      userId: 'usr-lab-1',
      name: 'Awadh Diagnostics & Advanced Pathology',
      address: 'TCG 3/3, Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      phone: '+91 522 409 8899',
      email: 'reports@awadhdiagnostics.com',
      licenseNo: 'NABL-UP-MC-2022-881',
      accreditation: 'NABL Accredited & ICMR Approved Reference Lab',
      isVerified: true,
      rating: 4.9,
      reviewCount: 380,
      turnaroundTimeNote: '4-6 hours express reporting with pathologist tele-consultation',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-6',
      userId: 'usr-lab-1',
      name: 'Pathkind Diagnostics Regional Reference Lab',
      address: 'Commercial Complex, Sector 14, Ring Road, Vikas Nagar',
      city: 'Lucknow',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8980,
      longitude: 80.9510,
      phone: '+91 522 660 1122',
      email: 'lucknow.ops@pathkindlabs.com',
      licenseNo: 'NABL-UP-PKD-2021-992',
      accreditation: 'NABL Accredited & ISO Certified High-Volume Testing Centre',
      isVerified: true,
      rating: 4.8,
      reviewCount: 290,
      turnaroundTimeNote: '6-10 hours digital TAT with free Lucknow doorstep sample pickup',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-7',
      userId: 'usr-lab-1',
      name: 'Metropolis Healthcare South Lucknow Hub',
      address: 'Sector G, Ashiyana, Near Power House Chauraha',
      city: 'Lucknow',
      area: 'Ashiyana & South City',
      latitude: 26.7910,
      longitude: 80.9120,
      phone: '+91 522 411 9900',
      email: 'ashiyana@metropolisindia.com',
      licenseNo: 'NABL-UP-MET-2023-771',
      accreditation: 'NABL & CAP Certified Comprehensive Pathology Network',
      isVerified: true,
      rating: 4.9,
      reviewCount: 310,
      turnaroundTimeNote: 'Same day reporting by senior MD pathologists',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-8',
      userId: 'usr-lab-1',
      name: 'Redcliffe Labs Chowk Diagnostic Centre',
      address: 'Victoria Street, Near Medical College Chauraha, Chowk',
      city: 'Lucknow',
      area: 'Chowk & Old Lucknow',
      latitude: 26.8680,
      longitude: 80.9080,
      phone: '+91 522 350 4400',
      email: 'chowk@redcliffelabs.com',
      licenseNo: 'NABL-UP-RCL-2022-224',
      accreditation: 'NABL Certified Automated Diagnostic Facility',
      isVerified: true,
      rating: 4.8,
      reviewCount: 270,
      turnaroundTimeNote: 'Smart report delivery within 8 hours on WhatsApp & email',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const diagnosticTests: DiagnosticTest[] = [
    {
      id: 'test-1',
      labId: 'lab-1',
      name: 'Comprehensive Lipid Profile with Cardiac Risk Ratio',
      code: 'LKO-LPD-01',
      category: 'Cardiology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 650.0,
      discountPrice: 499.0,
      preparationInstructions: 'Fasting of 10 to 12 hours is mandatory. Water is permitted.',
      description: 'Measures Total Cholesterol, Direct HDL, Calculated LDL, Triglycerides, VLDL, and Total/HDL Chol Ratio. Essential for heart disease prevention.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol (Direct)', unit: 'mg/dL', normalRange: '> 40 (M), > 50 (F)' },
        { name: 'LDL Cholesterol', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' },
        { name: 'Total Cholesterol / HDL Ratio', unit: 'Ratio', normalRange: '3.0 - 5.0' },
        { name: 'hs-CRP (Cardiac Inflammation)', unit: 'mg/L', normalRange: '< 1.0 (Low Risk)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-2',
      labId: 'lab-2',
      name: 'Standard Lipid Profile Screening',
      code: 'LKO-LPD-02',
      category: 'Cardiology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 500.0,
      discountPrice: 399.0,
      preparationInstructions: 'Strict 10-12 hour fasting required prior to blood draw.',
      description: 'Standard lipid profile test measuring cardiovascular risk factors at Aliganj central lab.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol', unit: 'mg/dL', normalRange: '> 40' },
        { name: 'LDL Cholesterol', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-3',
      labId: 'lab-3',
      name: 'Comprehensive Metabolic & Renal Function Panel (KFT + LFT)',
      code: 'LKO-KFT-LFT-01',
      category: 'Biochemistry',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 850.0,
      discountPrice: 650.0,
      preparationInstructions: 'Fasting 8-10 hours recommended.',
      description: 'Complete biochemical assessment evaluating kidney parameters (Urea, Creatinine, Uric Acid, eGFR) and liver enzymes (Bilirubin, SGOT, SGPT, Alkaline Phosphatase).',
      parametersJson: JSON.stringify([
        { name: 'Fasting Plasma Glucose', unit: 'mg/dL', normalRange: '70 - 99' },
        { name: 'Blood Urea', unit: 'mg/dL', normalRange: '15 - 40' },
        { name: 'Serum Creatinine', unit: 'mg/dL', normalRange: '0.6 - 1.2' },
        { name: 'Serum Uric Acid', unit: 'mg/dL', normalRange: '3.5 - 7.2' },
        { name: 'Total Bilirubin', unit: 'mg/dL', normalRange: '0.2 - 1.2' },
        { name: 'SGPT (ALT)', unit: 'U/L', normalRange: '0 - 45' },
        { name: 'SGOT (AST)', unit: 'U/L', normalRange: '0 - 40' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-4',
      labId: 'lab-1',
      name: 'HbA1c Glycated Hemoglobin with Average Estimated Glucose',
      code: 'LKO-GLY-A1C',
      category: 'Diabetes',
      sampleType: 'Whole Blood EDTA',
      turnaroundHours: 4,
      price: 550.0,
      discountPrice: 399.0,
      preparationInstructions: 'No fasting required. Sample can be collected at any time.',
      description: 'Gold standard automated HPLC test reflecting 3-month blood sugar control for diabetic monitoring.',
      parametersJson: JSON.stringify([
        { name: 'HbA1c', unit: '%', normalRange: '< 5.7 (Normal), 5.7 - 6.4 (Prediabetes)' },
        { name: 'Estimated Average Glucose (eAG)', unit: 'mg/dL', normalRange: '90 - 120' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-5',
      labId: 'lab-2',
      name: 'Thyroid Function Profile Total (T3, T4, TSH Ultra-Sensitive)',
      code: 'LKO-THY-TOT',
      category: 'Thyroid',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 600.0,
      discountPrice: 420.0,
      preparationInstructions: 'Morning collection advised. Do not take thyroid medication until after sample collection.',
      description: 'Evaluates hyperthyroidism and hypothyroidism functionality using ultra-sensitive chemiluminescence assay.',
      parametersJson: JSON.stringify([
        { name: 'TSH (Ultrasensitive)', unit: 'uIU/mL', normalRange: '0.35 - 4.94' },
        { name: 'Total T3 (Triiodothyronine)', unit: 'ng/dL', normalRange: '80 - 200' },
        { name: 'Total T4 (Thyroxine)', unit: 'ug/dL', normalRange: '5.1 - 14.1' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-6',
      labId: 'lab-5',
      name: 'Complete Blood Count (CBC) with ESR & Automated Smear',
      code: 'LKO-CBC-ESR',
      category: 'Hematology',
      sampleType: 'Whole Blood EDTA',
      turnaroundHours: 4,
      price: 400.0,
      discountPrice: 280.0,
      preparationInstructions: 'No special preparation needed. Fasting not required.',
      description: '28-parameter automated hemogram evaluating anemia, infections, platelet counts, and inflammatory ESR.',
      parametersJson: JSON.stringify([
        { name: 'Hemoglobin', unit: 'g/dL', normalRange: '13.0 - 17.0 (M), 12.0 - 15.0 (F)' },
        { name: 'Total Leukocyte Count (TLC)', unit: '/cumm', normalRange: '4,000 - 11,000' },
        { name: 'Platelet Count', unit: 'lakh/cumm', normalRange: '1.5 - 4.5' },
        { name: 'ESR (Westergren)', unit: 'mm/1st hr', normalRange: '0 - 15' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-7',
      labId: 'lab-4',
      name: 'Vitamin D 25-Hydroxy Total (Chemiluminescence CLIA)',
      code: 'LKO-VIT-D3',
      category: 'Vitamins',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 1200.0,
      discountPrice: 850.0,
      preparationInstructions: 'No fasting required. Morning sample preferred.',
      description: 'Accurate quantitative detection of 25-OH Vitamin D2 and D3 for bone mineralization, osteoporosis screening, and immune status.',
      parametersJson: JSON.stringify([
        { name: '25-Hydroxy Vitamin D', unit: 'ng/mL', normalRange: '30.0 - 100.0 (Sufficient)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-8',
      labId: 'lab-4',
      name: 'Vitamin B12 (Cyanocobalamin) Assay',
      code: 'LKO-VIT-B12',
      category: 'Vitamins',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 900.0,
      discountPrice: 650.0,
      preparationInstructions: '10-12 hour fasting recommended.',
      description: 'Investigates macrocytic anemia, peripheral tingling/neuropathy, memory decline, and chronic fatigue.',
      parametersJson: JSON.stringify([
        { name: 'Vitamin B12', unit: 'pg/mL', normalRange: '211 - 911' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-9',
      labId: 'lab-1',
      name: 'High-Sensitivity C-Reactive Protein (hs-CRP)',
      code: 'LKO-HS-CRP',
      category: 'Cardiology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 650.0,
      discountPrice: 480.0,
      preparationInstructions: 'Patient should be in a stable metabolic state without acute infection.',
      description: 'Ultra-sensitive vascular biomarker predicting coronary artery inflammation and atheroma plaque instability.',
      parametersJson: JSON.stringify([
        { name: 'hs-CRP', unit: 'mg/L', normalRange: '< 1.0 (Low Risk), 1.0 - 3.0 (Average Risk)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-10',
      labId: 'lab-3',
      name: 'Serum Ferritin & Complete Iron Binding Capacity (TIBC)',
      code: 'LKO-IRON-PAN',
      category: 'Hematology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 950.0,
      discountPrice: 699.0,
      preparationInstructions: 'Morning fasting blood sample required; avoid iron supplements 24h prior.',
      description: 'Differentiates iron deficiency anemia from chronic disease anemia; evaluates reticuloendothelial iron stores.',
      parametersJson: JSON.stringify([
        { name: 'Serum Iron', unit: 'ug/dL', normalRange: '65 - 175' },
        { name: 'Total Iron Binding Capacity (TIBC)', unit: 'ug/dL', normalRange: '250 - 450' },
        { name: 'Transferrin Saturation', unit: '%', normalRange: '20 - 50' },
        { name: 'Serum Ferritin', unit: 'ng/mL', normalRange: '30 - 400 (M), 13 - 150 (F)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-11',
      labId: 'lab-6',
      name: 'Kidney Function Test (KFT with Serum Electrolytes)',
      code: 'LKO-KFT-ELEC',
      category: 'Biochemistry',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 750.0,
      discountPrice: 550.0,
      preparationInstructions: 'Fasting 8-10 hours advised.',
      description: 'Comprehensive renal profile measuring Blood Urea, Serum Creatinine, Uric Acid, BUN, Sodium, Potassium, and Chloride.',
      parametersJson: JSON.stringify([
        { name: 'Blood Urea', unit: 'mg/dL', normalRange: '15 - 40' },
        { name: 'Serum Creatinine', unit: 'mg/dL', normalRange: '0.6 - 1.2' },
        { name: 'Serum Uric Acid', unit: 'mg/dL', normalRange: '3.5 - 7.0' },
        { name: 'Serum Sodium (Na+)', unit: 'mEq/L', normalRange: '136 - 145' },
        { name: 'Serum Potassium (K+)', unit: 'mEq/L', normalRange: '3.5 - 5.1' },
        { name: 'Serum Chloride (Cl-)', unit: 'mEq/L', normalRange: '98 - 107' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-12',
      labId: 'lab-5',
      name: 'Liver Function Test (LFT Comprehensive)',
      code: 'LKO-LFT-FULL',
      category: 'Biochemistry',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 700.0,
      discountPrice: 520.0,
      preparationInstructions: 'Overnight fasting of 8 hours recommended.',
      description: 'Full liver enzymatic breakdown: Bilirubin (Total, Direct, Indirect), SGOT/AST, SGPT/ALT, Alkaline Phosphatase, Total Protein, and Albumin/Globulin ratio.',
      parametersJson: JSON.stringify([
        { name: 'Bilirubin Total', unit: 'mg/dL', normalRange: '0.2 - 1.2' },
        { name: 'Bilirubin Direct', unit: 'mg/dL', normalRange: '0.0 - 0.3' },
        { name: 'SGOT (AST)', unit: 'U/L', normalRange: '5 - 40' },
        { name: 'SGPT (ALT)', unit: 'U/L', normalRange: '5 - 45' },
        { name: 'Alkaline Phosphatase (ALP)', unit: 'U/L', normalRange: '44 - 147' },
        { name: 'Serum Albumin', unit: 'g/dL', normalRange: '3.5 - 5.2' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-13',
      labId: 'lab-7',
      name: 'Urine Routine & Microscopic Examination (R/M)',
      code: 'LKO-URN-RM',
      category: 'Pathology',
      sampleType: 'Clean Catch Midstream Urine',
      turnaroundHours: 3,
      price: 200.0,
      discountPrice: 150.0,
      preparationInstructions: 'Collect early morning mid-stream clean catch sample in sterile container provided.',
      description: 'Physical, chemical, and microscopic examination detecting UTI, proteinuria, hematuria, and renal casts.',
      parametersJson: JSON.stringify([
        { name: 'Urine Specific Gravity', unit: 'Ratio', normalRange: '1.005 - 1.030' },
        { name: 'Urine pH', unit: 'pH', normalRange: '5.0 - 7.5' },
        { name: 'Urine Protein / Albumin', unit: '', normalRange: 'Nil / Negative' },
        { name: 'Urine Sugar / Glucose', unit: '', normalRange: 'Nil / Negative' },
        { name: 'Pus Cells (Leukocytes)', unit: '/HPF', normalRange: '0 - 5' },
        { name: 'Red Blood Cells (RBCs)', unit: '/HPF', normalRange: '0 - 2' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-14',
      labId: 'lab-8',
      name: 'Dengue Serology (NS1 Antigen + IgM + IgG Antibodies)',
      code: 'LKO-DNG-TRI',
      category: 'Infectious Disease',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 4,
      price: 1100.0,
      discountPrice: 750.0,
      preparationInstructions: 'No fasting required. Emergency processing available across Lucknow.',
      description: 'Rapid, confirmatory differential ELISA assay detecting acute Dengue NS1 antigen (days 1-5) and secondary immune antibodies.',
      parametersJson: JSON.stringify([
        { name: 'Dengue NS1 Antigen', unit: 'Index', normalRange: '< 0.9 (Negative)' },
        { name: 'Dengue IgM Antibody', unit: 'Index', normalRange: '< 0.9 (Negative)' },
        { name: 'Dengue IgG Antibody', unit: 'Index', normalRange: '< 0.9 (Negative)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-15',
      labId: 'lab-1',
      name: 'Prostate Specific Antigen (PSA) Total',
      code: 'LKO-PSA-TOT',
      category: 'Oncology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 1000.0,
      discountPrice: 799.0,
      preparationInstructions: 'Avoid vigorous cycling or ejaculation 48 hours prior to blood draw.',
      description: 'Screening marker for benign prostatic hyperplasia (BPH) and adenocarcinoma of the prostate in men aged 45+.',
      parametersJson: JSON.stringify([
        { name: 'Total PSA', unit: 'ng/mL', normalRange: '< 4.0' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-16',
      labId: 'lab-3',
      name: 'D-Dimer Quantitative Assay (Cardiac & Thrombosis Marker)',
      code: 'LKO-DDM-QUANT',
      category: 'Cardiology',
      sampleType: 'Citrated Plasma',
      turnaroundHours: 4,
      price: 1400.0,
      discountPrice: 999.0,
      preparationInstructions: 'No special preparation needed. Emergency sample processing.',
      description: 'Excludes deep vein thrombosis (DVT), pulmonary embolism (PE), and evaluates systemic hypercoagulable states.',
      parametersJson: JSON.stringify([
        { name: 'D-Dimer', unit: 'ug/mL FEU', normalRange: '< 0.50' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-17',
      labId: 'lab-5',
      name: 'Executive Full Body Health Checkup Package (68 Parameters)',
      code: 'LKO-EXC-FULL',
      category: 'Wellness Packages',
      sampleType: 'Serum + Whole Blood + Urine',
      turnaroundHours: 12,
      price: 2499.0,
      discountPrice: 1499.0,
      preparationInstructions: 'Overnight fasting of 10-12 hours mandatory. Free home sample collection in Lucknow.',
      description: 'Comprehensive whole-body diagnostic package: CBC (28), Complete Lipid (7), KFT (6), LFT (11), HbA1c (2), Thyroid TSH (1), Urine (13).',
      parametersJson: JSON.stringify([
        { name: 'CBC Profile', unit: 'Parameters', normalRange: '28 Tests Included' },
        { name: 'Lipid Profile', unit: 'Parameters', normalRange: '7 Tests Included' },
        { name: 'Liver & Renal Profiles', unit: 'Parameters', normalRange: '17 Tests Included' },
        { name: 'Diabetes (HbA1c & Fasting)', unit: 'Parameters', normalRange: '2 Tests Included' },
        { name: 'Urine Routine & Microscopic', unit: 'Parameters', normalRange: '13 Tests Included' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-18',
      labId: 'lab-2',
      name: 'Senior Citizen Complete Wellness Package (84 Parameters)',
      code: 'LKO-SNR-WELL',
      category: 'Wellness Packages',
      sampleType: 'Serum + Whole Blood + Urine',
      turnaroundHours: 12,
      price: 3600.0,
      discountPrice: 2299.0,
      preparationInstructions: '10-12 hours fasting required. Free home blood and urine collection with senior-friendly phlebotomists.',
      description: 'Master preventive health checkup for adults 50+: Includes Vitamin D3, Vitamin B12, Cardiac Risk Ratio, Full KFT/LFT, Complete Hemogram, and Urine R/M.',
      parametersJson: JSON.stringify([
        { name: 'Vitamin D3 & B12', unit: 'Parameters', normalRange: '2 Essential Vitamins' },
        { name: 'Metabolic & Electrolyte Panel', unit: 'Parameters', normalRange: 'Complete KFT + LFT' },
        { name: 'Cardiac & Lipid Screening', unit: 'Parameters', normalRange: 'Full Lipid Panel' },
        { name: 'Glycemic Status (HbA1c)', unit: 'Parameters', normalRange: '3-Month Average' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const queues: Queue[] = [
    { id: 'q-1', doctorId: 'doc-prof-1', clinicId: 'cln-1', date: todayStr, currentTokenNumber: 8, totalTokensIssued: 22, estimatedWaitTimeMinutes: 12, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-2', doctorId: 'doc-prof-2', clinicId: 'cln-1', date: todayStr, currentTokenNumber: 5, totalTokensIssued: 16, estimatedWaitTimeMinutes: 20, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-3', doctorId: 'doc-prof-3', clinicId: 'cln-3', date: todayStr, currentTokenNumber: 11, totalTokensIssued: 26, estimatedWaitTimeMinutes: 15, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-4', doctorId: 'doc-prof-4', clinicId: 'cln-2', date: todayStr, currentTokenNumber: 6, totalTokensIssued: 18, estimatedWaitTimeMinutes: 18, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-5', doctorId: 'doc-prof-5', clinicId: 'cln-2', date: todayStr, currentTokenNumber: 9, totalTokensIssued: 24, estimatedWaitTimeMinutes: 10, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-6', doctorId: 'doc-prof-6', clinicId: 'cln-7', date: todayStr, currentTokenNumber: 14, totalTokensIssued: 30, estimatedWaitTimeMinutes: 22, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-7', doctorId: 'doc-prof-7', clinicId: 'cln-5', date: todayStr, currentTokenNumber: 7, totalTokensIssued: 19, estimatedWaitTimeMinutes: 14, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-8', doctorId: 'doc-prof-8', clinicId: 'cln-8', date: todayStr, currentTokenNumber: 12, totalTokensIssued: 28, estimatedWaitTimeMinutes: 16, status: 'OPEN', createdAt: now, updatedAt: now },
    { id: 'q-9', doctorId: 'doc-prof-9', clinicId: 'cln-4', date: todayStr, currentTokenNumber: 4, totalTokensIssued: 15, estimatedWaitTimeMinutes: 25, status: 'OPEN', createdAt: now, updatedAt: now }
  ];

  const queueTickets: QueueTicket[] = [
    { id: 'tkt-1', queueId: 'q-1', patientId: 'pat-prof-1', tokenNumber: 9, estimatedTime: '10:45 AM', status: 'CALLED', createdAt: now, updatedAt: now },
    { id: 'tkt-2', queueId: 'q-1', patientId: 'pat-prof-1', tokenNumber: 10, estimatedTime: '11:00 AM', status: 'WAITING', createdAt: now, updatedAt: now },
    { id: 'tkt-3', queueId: 'q-3', patientId: 'pat-prof-1', tokenNumber: 12, estimatedTime: '11:30 AM', status: 'WAITING', createdAt: now, updatedAt: now }
  ];

  const appointments: Appointment[] = [
    {
      id: 'apt-1',
      patientId: 'pat-prof-1',
      doctorId: 'doc-prof-1',
      clinicId: 'cln-1',
      date: todayStr,
      timeSlot: '10:30 AM',
      type: 'IN_PERSON',
      status: 'CONFIRMED',
      symptoms: 'Routine 6-month blood pressure review, periodic mild palpitation post-exertion.',
      notes: 'Patient advised to bring past ECG and lipid profile reports.',
      fee: 800.0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'apt-2',
      patientId: 'pat-prof-1',
      doctorId: 'doc-prof-3',
      clinicId: 'cln-3',
      date: todayStr,
      timeSlot: '04:00 PM',
      type: 'IN_PERSON',
      status: 'CONFIRMED',
      symptoms: 'Diabetes glycemic control assessment; fasting sugars hovering near 128 mg/dL.',
      notes: 'Review HbA1c and titration of oral hypoglycemics.',
      fee: 700.0,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const referrals: Referral[] = [
    {
      id: 'ref-1',
      patientId: 'pat-prof-1',
      referringDoctorId: 'doc-prof-1',
      referredDoctorId: 'doc-prof-3',
      reason: 'Elevated fasting blood sugar (132 mg/dL) noted during annual cardiac risk evaluation. Kindly assess for prediabetes metabolic syndrome.',
      diagnosis: 'Pre-diabetes & Metabolic Syndrome Workup',
      status: 'ISSUED',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const testBookings: TestBooking[] = [
    {
      id: 'tb-1',
      patientId: 'pat-prof-1',
      testId: 'test-1',
      labId: 'lab-1',
      appointmentDate: todayStr,
      timeSlot: '08:30 AM',
      collectionType: 'HOME_COLLECTION',
      collectionAddress: 'B-4/112, Sector 4, Gomti Nagar, Lucknow, UP',
      status: 'SAMPLE_COLLECTED',
      totalAmount: 499.0,
      barcode: 'BC-LKO-2026-901',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'tb-2',
      patientId: 'pat-prof-1',
      testId: 'test-4',
      labId: 'lab-1',
      appointmentDate: todayStr,
      timeSlot: '08:30 AM',
      collectionType: 'HOME_COLLECTION',
      collectionAddress: 'B-4/112, Sector 4, Gomti Nagar, Lucknow, UP',
      status: 'PROCESSING',
      totalAmount: 399.0,
      barcode: 'BC-LKO-2026-902',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const samples: Sample[] = [
    {
      id: 'smp-1',
      bookingId: 'tb-1',
      barcode: 'BC-LKO-2026-901',
      sampleType: 'Serum (Venous Blood)',
      collectedAt: now,
      receivedAtLab: now,
      status: 'TESTING_IN_PROGRESS',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'smp-2',
      bookingId: 'tb-2',
      barcode: 'BC-LKO-2026-902',
      sampleType: 'Whole Blood EDTA',
      collectedAt: now,
      receivedAtLab: now,
      status: 'RECEIVED_AT_LAB',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const medicalReports: MedicalReport[] = [
    {
      id: 'rep-1',
      patientId: 'pat-prof-1',
      testBookingId: 'tb-1',
      testName: 'Comprehensive Lipid Profile with Cardiac Risk Ratio',
      labName: 'Dr. Lal PathLabs National Reference Hub',
      fileUrl: '/mock-reports/lipid-profile.pdf',
      extractedFacts: [
        { parameter: 'Total Cholesterol', value: '218', unit: 'mg/dL', normalRange: '125 - 200', interpretation: 'BORDERLINE_HIGH' },
        { parameter: 'Direct HDL Cholesterol', value: '38', unit: 'mg/dL', normalRange: '> 40', interpretation: 'LOW' },
        { parameter: 'Calculated LDL Cholesterol', value: '142', unit: 'mg/dL', normalRange: '< 100', interpretation: 'HIGH' },
        { parameter: 'Triglycerides', value: '188', unit: 'mg/dL', normalRange: '< 150', interpretation: 'HIGH' },
        { parameter: 'Cholesterol / HDL Ratio', value: '5.7', unit: 'Ratio', normalRange: '3.0 - 5.0', interpretation: 'ABNORMAL' }
      ],
      aiAnalysis: {
        summary: 'Dyslipidemia detected with elevated total cholesterol (218 mg/dL), elevated triglycerides (188 mg/dL), and suboptimal protective HDL (38 mg/dL). These findings suggest moderate atherosclerotic cardiovascular risk requiring dietary fat modification and clinical evaluation.',
        keyFindings: [
          'Total Cholesterol is mildly elevated at 218 mg/dL (optimal < 200 mg/dL).',
          'Triglycerides are elevated at 188 mg/dL reflecting dietary carbohydrate and fat processing.',
          'Cardiovascular risk ratio of 5.7 indicates need for physician consultation.'
        ],
        lifestyleAdvice: [
          'Adopt a heart-healthy diet rich in soluble fiber (oats, fenugreek, flaxseeds).',
          'Reduce saturated fats, vanaspati ghee, and deep-fried savory snacks.',
          'Engage in 30-45 minutes of brisk walking along Gomti Riverfront or residential parks at least 5 days weekly.'
        ],
        matchedSpecialty: 'Cardiology',
        suggestedSpecialists: [
          { name: 'Dr. Ananya Srivastava, MD, DM', specialty: 'Cardiology', clinicName: 'Awadh Mediplex & Heart Institute' },
          { name: 'Dr. Rishi Sethi, MD, DM', specialty: 'Cardiology', clinicName: 'Charak Medical Centre & KGMU Corridor' }
        ]
      },
      isVerifiedByPathologist: true,
      verifiedBy: 'Dr. R. K. Saxena, MD (Pathology), NABL Signatory',
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const reviews: Review[] = [
    { id: 'rev-1', userId: 'usr-pat-1', targetType: 'DOCTOR', targetId: 'doc-prof-1', rating: 5, comment: 'Dr. Ananya Srivastava is exceptionally thorough and patient. She explained my cardiac risk score and adjusted my medication without unnecessary tests.', isVerifiedPatient: true, createdAt: now },
    { id: 'rev-2', userId: 'usr-pat-1', targetType: 'DOCTOR', targetId: 'doc-prof-3', rating: 5, comment: 'Dr. Priya Mehrotra in Kapoorthala is an outstanding endocrinologist! Her guidance on diabetes diet and insulin timing has brought my HbA1c under control.', isVerifiedPatient: true, createdAt: now },
    { id: 'rev-3', userId: 'usr-pat-1', targetType: 'LABORATORY', targetId: 'lab-1', rating: 5, comment: 'Punctual home sample collection in Gomti Nagar. The phlebotomist arrived right at 7:30 AM with cold transport container. Report was ready by 2 PM.', isVerifiedPatient: true, createdAt: now },
    { id: 'rev-4', userId: 'usr-pat-1', targetType: 'DOCTOR', targetId: 'doc-prof-4', rating: 5, comment: 'Dr. Manish Verma accurately diagnosed my chronic vestibular migraine after months of wandering around different hospitals. Highly recommended.', isVerifiedPatient: true, createdAt: now },
    { id: 'rev-5', userId: 'usr-pat-1', targetType: 'DOCTOR', targetId: 'doc-prof-6', rating: 5, comment: 'Dr. Rishi Sethi is a lifesaver. His clinical judgment during my father angiography in Chowk was unparalleled.', isVerifiedPatient: true, createdAt: now }
  ];

  const notifications: Notification[] = [
    { id: 'notif-1', userId: 'usr-pat-1', title: 'Token #9 is Next in Live Queue', message: 'Dr. Ananya Srivastava is now seeing Token #8. Please be seated near Chamber 102 at Awadh Mediplex.', type: 'QUEUE_UPDATE', isRead: false, link: '/patient/appointments', createdAt: now },
    { id: 'notif-2', userId: 'usr-pat-1', title: 'Diagnostic Report Ready', message: 'Your Comprehensive Lipid Profile report from Dr. Lal PathLabs has been verified by the chief pathologist and analyzed by AI.', type: 'REPORT_READY', isRead: false, link: '/patient/reports', createdAt: now }
  ];

  const auditLogs: AuditLog[] = [
    { id: 'aud-1', userId: 'usr-admin-1', userRole: 'ADMIN', action: 'PROVIDER_VERIFICATION_APPROVED', resourceType: 'DOCTOR_LICENSE', resourceId: 'UPMC-54210', detailsJson: JSON.stringify({ doctor: 'Dr. Ananya Srivastava', status: 'VERIFIED', stateCouncil: 'UP Medical Council' }), ipAddress: '127.0.0.1', userAgent: 'MediLink Internal Audit Engine', createdAt: now },
    { id: 'aud-2', userId: 'usr-admin-1', userRole: 'ADMIN', action: 'LAB_ACCREDITATION_VERIFIED', resourceType: 'NABL_CERTIFICATE', resourceId: 'NABL-UP-LAL-2022-881', detailsJson: JSON.stringify({ lab: 'Dr. Lal PathLabs Reference Hub', accreditation: 'NABL & CAP' }), ipAddress: '127.0.0.1', userAgent: 'MediLink Internal Audit Engine', createdAt: now }
  ];

  return {
    users,
    patientProfiles,
    doctorProfiles,
    clinics,
    clinicDoctors,
    laboratories,
    diagnosticTests,
    appointments,
    queues,
    queueTickets,
    referrals,
    testBookings,
    samples,
    medicalReports,
    reviews,
    notifications,
    auditLogs
  };
}
'''

with open('server/db/seedData.ts', 'w') as f:
    f.write(seed_content)

# Remove old db.json so store re-generates fresh from seedData
if os.path.exists('data/db.json'):
    os.remove('data/db.json')
    print('Removed old data/db.json')

print('Generated server/db/seedData.ts with real Lucknow data successfully')
