import bcrypt from 'bcryptjs';
import {
  User,
  PatientProfile,
  DoctorProfile,
  Clinic,
  ClinicDoctor,
  Laboratory,
  DiagnosticTest,
  Appointment,
  Queue,
  QueueTicket,
  Referral,
  TestBooking,
  Sample,
  MedicalReport,
  Review,
  Notification,
  AuditLog
} from '../types/index.js';

export function getInitialSeedData() {
  const salt = bcrypt.genSaltSync(10);
  const passwordAdmin = bcrypt.hashSync('Admin@123', salt);
  const passwordPatient = bcrypt.hashSync('Patient@123', salt);
  const passwordDoctor = bcrypt.hashSync('Doctor@123', salt);
  const passwordClinic = bcrypt.hashSync('Clinic@123', salt);
  const passwordLab = bcrypt.hashSync('Lab@123', salt);

  const now = new Date().toISOString();
  const todayStr = new Date().toISOString().split('T')[0];

  const users: User[] = [
    {
      id: 'usr-admin-1',
      email: 'admin@medilink.com',
      passwordHash: passwordAdmin,
      name: 'MediLink Platform Admin',
      role: 'ADMIN',
      phone: '+1 (555) 019-2831',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-pat-1',
      email: 'patient@medilink.com',
      passwordHash: passwordPatient,
      name: 'Johnathan Miller',
      role: 'PATIENT',
      phone: '+1 (555) 349-1102',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-1',
      email: 'doctor.sarah@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Sarah Jenkins, MD, FACC',
      role: 'DOCTOR',
      phone: '+1 (555) 438-9201',
      avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-2',
      email: 'marcus.vance@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Marcus Vance, MD',
      role: 'DOCTOR',
      phone: '+1 (555) 672-9901',
      avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-3',
      email: 'elena.rostova@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Elena Rostova, MD',
      role: 'DOCTOR',
      phone: '+1 (555) 781-3344',
      avatarUrl: 'https://images.unsplash.com/photo-1594824813524-1188fb8556f2?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-clinic-1',
      email: 'admin@metroclinic.com',
      passwordHash: passwordClinic,
      name: 'Metro Health Specialist Center',
      role: 'CLINIC',
      phone: '+1 (555) 902-1200',
      avatarUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-lab-1',
      email: 'manager@precisionlab.com',
      passwordHash: passwordLab,
      name: 'Precision Diagnostics & Pathology',
      role: 'LABORATORY',
      phone: '+1 (555) 234-8899',
      avatarUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-lab-2',
      email: 'care@apexbiolabs.com',
      passwordHash: passwordLab,
      name: 'Apex Bio-Tech Laboratories',
      role: 'LABORATORY',
      phone: '+1 (555) 441-2388',
      avatarUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const patientProfiles: PatientProfile[] = [
    {
      id: 'pat-prof-1',
      userId: 'usr-pat-1',
      dob: '1988-06-14',
      gender: 'Male',
      bloodGroup: 'O+',
      allergies: 'Penicillin, Shellfish',
      emergencyContact: 'Emily Miller (+1 555-349-1105)',
      address: '742 Evergreen Terrace, Springfield, OR',
      medicalHistoryJson: JSON.stringify([
        { condition: 'Mild Essential Hypertension', diagnosedYear: 2021, status: 'Managed' },
        { condition: 'Seasonal Allergic Rhinitis', diagnosedYear: 2018, status: 'Active' }
      ]),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinics: Clinic[] = [
    {
      id: 'cln-1',
      userId: 'usr-clinic-1',
      name: 'Metro Health Specialist Center',
      address: '100 Medical Center Way, Suite 400',
      city: 'Portland, OR',
      area: 'Downtown / Pearl District',
      latitude: 45.5231,
      longitude: -122.6765,
      phone: '+1 (555) 902-1200',
      email: 'admin@metroclinic.com',
      registrationNo: 'OR-MED-2022-9081',
      servicesJson: JSON.stringify(['Cardiology', 'Neurology', 'Endocrinology', 'Executive Health Checkups', 'Ultrasound & ECG']),
      facilitiesJson: JSON.stringify(['Wheelchair Accessible', 'On-site Pharmacy', 'Digital X-Ray', 'Express Blood Draw', 'Free Parking']),
      openingTime: '08:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 142,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-2',
      userId: 'usr-clinic-1',
      name: 'Westside Outpatient & Diagnostic Pavilion',
      address: '14250 SW Science Park Drive',
      city: 'Beaverton, OR',
      area: 'Beaverton Tech Corridor',
      latitude: 45.4871,
      longitude: -122.8037,
      phone: '+1 (555) 831-4400',
      email: 'westside@metroclinic.com',
      registrationNo: 'OR-MED-2023-4102',
      servicesJson: JSON.stringify(['Cardiovascular Health', 'Preventive Screening', 'Neurology Clinic', 'Physical Therapy']),
      facilitiesJson: JSON.stringify(['EV Charging Stations', 'Pediatric Area', 'Specimen Drop-off', 'Walk-in Triage']),
      openingTime: '07:30',
      closingTime: '19:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 98,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-3',
      userId: 'usr-clinic-1',
      name: 'Lake Oswego Specialty Care Center',
      address: '400 Kruse Way, Suite 210',
      city: 'Lake Oswego, OR',
      area: 'Lake Oswego / South Metro',
      latitude: 45.4207,
      longitude: -122.6706,
      phone: '+1 (555) 670-3322',
      email: 'lakeoswego@metroclinic.com',
      registrationNo: 'OR-MED-2021-3319',
      servicesJson: JSON.stringify(['Endocrinology & Diabetes', 'Holistic Preventive Medicine', 'Metabolic Health']),
      facilitiesJson: JSON.stringify(['Private Consultation Suites', 'Diagnostic Lab', 'Valet Parking']),
      openingTime: '08:30',
      closingTime: '18:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 115,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const doctorProfiles: DoctorProfile[] = [
    {
      id: 'doc-prof-1',
      userId: 'usr-doc-1',
      specialty: 'Cardiology',
      subSpecialty: 'Interventional & Preventive Cardiology',
      experienceYears: 14,
      qualification: 'MBBS, MD (Cardiology), FACC',
      licenseNumber: 'MD-OR-882910',
      consultationFee: 120.0,
      bio: 'Board-certified cardiologist specializing in preventive cardiovascular care, hypertension management, lipid disorders, and non-invasive cardiac imaging.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 96,
      clinicId: 'cln-1',
      area: 'Downtown / Pearl District',
      latitude: 45.5231,
      longitude: -122.6765,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-2',
      userId: 'usr-doc-2',
      specialty: 'Neurology',
      subSpecialty: 'Headache Medicine & Neurovascular Disorders',
      experienceYears: 11,
      qualification: 'MD (Neurology), FAAN',
      licenseNumber: 'MD-OR-774019',
      consultationFee: 140.0,
      bio: 'Senior Neurologist with extensive research in migraine pathophysiology, cognitive assessment, neuropathies, and stroke prevention.',
      consultationDuration: 30,
      rating: 4.8,
      reviewCount: 64,
      clinicId: 'cln-2',
      area: 'Beaverton Tech Corridor',
      latitude: 45.4871,
      longitude: -122.8037,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Wednesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-3',
      userId: 'usr-doc-3',
      specialty: 'Endocrinology',
      subSpecialty: 'Type 1 & 2 Diabetes, Thyroid & Metabolic Disorders',
      experienceYears: 9,
      qualification: 'MD, FACE (Endocrinology)',
      licenseNumber: 'MD-OR-902341',
      consultationFee: 110.0,
      bio: 'Dedicated endocrinologist focusing on holistic metabolic health, continuous glucose monitoring integration, and personalized thyroid therapy.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 82,
      clinicId: 'cln-3',
      area: 'Lake Oswego / South Metro',
      latitude: 45.4207,
      longitude: -122.6706,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinicDoctors: ClinicDoctor[] = [
    {
      id: 'cln-doc-1',
      clinicId: 'cln-1',
      doctorId: 'doc-prof-1',
      daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
      roomNo: 'Suite 402 - Cardio Wing',
      status: 'ACTIVE',
      createdAt: now,
    },
    {
      id: 'cln-doc-2',
      clinicId: 'cln-2',
      doctorId: 'doc-prof-2',
      daysAvailableJson: JSON.stringify(['Tuesday', 'Wednesday', 'Thursday', 'Saturday']),
      roomNo: 'Suite 104 - Neuro Wing',
      status: 'ACTIVE',
      createdAt: now,
    },
    {
      id: 'cln-doc-3',
      clinicId: 'cln-3',
      doctorId: 'doc-prof-3',
      daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday']),
      roomNo: 'Suite 210 - Endocrine Dept',
      status: 'ACTIVE',
      createdAt: now,
    }
  ];

  const laboratories: Laboratory[] = [
    {
      id: 'lab-1',
      userId: 'usr-lab-1',
      name: 'Precision Diagnostics & Pathology',
      address: '220 Tech Park Blvd, Bldg C',
      city: 'Portland, OR',
      area: 'Eastside Medical Tech Park',
      latitude: 45.5152,
      longitude: -122.6587,
      phone: '+1 (555) 234-8899',
      email: 'manager@precisionlab.com',
      licenseNo: 'CLIA-OR-9912401',
      accreditation: 'CAP & CLIA Accredited Laboratory',
      isVerified: true,
      rating: 4.9,
      reviewCount: 210,
      turnaroundTimeNote: '12-24 hours for routine panels',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-2',
      userId: 'usr-lab-2',
      name: 'Apex Bio-Tech Laboratories',
      address: '550 Innovation Parkway, Suite 10',
      city: 'Beaverton, OR',
      area: 'Beaverton Tech Corridor',
      latitude: 45.4925,
      longitude: -122.8120,
      phone: '+1 (555) 441-2388',
      email: 'care@apexbiolabs.com',
      licenseNo: 'CLIA-OR-8823190',
      accreditation: 'ISO 15189 Certified & CLIA',
      isVerified: true,
      rating: 4.7,
      reviewCount: 165,
      turnaroundTimeNote: '24-36 hours standard TAT',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const diagnosticTests: DiagnosticTest[] = [
    {
      id: 'test-1',
      labId: 'lab-1',
      name: 'Advanced Lipid & Cardiovascular Biomarkers',
      code: 'LPD-ADV-01',
      category: 'Cardiology & Lipidology',
      sampleType: 'Serum (Blood)',
      turnaroundHours: 12,
      price: 85.0,
      discountPrice: 65.0,
      preparationInstructions: 'Strict 10-12 hour fasting required. Water is permitted.',
      description: 'Comprehensive assessment of Total Cholesterol, LDL-C, Direct HDL-C, Triglycerides, Non-HDL, and hs-CRP inflammatory marker.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol', unit: 'mg/dL', normalRange: '> 40 (Male), > 50 (Female)' },
        { name: 'LDL Cholesterol (Calculated)', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' },
        { name: 'hs-CRP (Cardiac Risk)', unit: 'mg/L', normalRange: '< 1.0 (Low Risk)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-2',
      labId: 'lab-2',
      name: 'Lipid Panel Standard',
      code: 'LPD-STD-02',
      category: 'Cardiology & Lipidology',
      sampleType: 'Serum (Blood)',
      turnaroundHours: 24,
      price: 55.0,
      discountPrice: 45.0,
      preparationInstructions: 'Fasting 12 hours prior to collection.',
      description: 'Standard lipid profile test measuring cardiovascular risk factors.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol', unit: 'mg/dL', normalRange: '> 40' },
        { name: 'LDL Cholesterol', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-3',
      labId: 'lab-1',
      name: 'Comprehensive Metabolic Panel (CMP-14)',
      code: 'CMP-14-PL',
      category: 'Biochemistry & Renal/Hepatic',
      sampleType: 'Serum (Blood)',
      turnaroundHours: 12,
      price: 70.0,
      discountPrice: 55.0,
      preparationInstructions: 'Fasting for 8-12 hours prior to test.',
      description: 'Evaluates kidney function, liver health, blood sugar, and electrolyte & fluid balance.',
      parametersJson: JSON.stringify([
        { name: 'Fasting Glucose', unit: 'mg/dL', normalRange: '70 - 99' },
        { name: 'Blood Urea Nitrogen (BUN)', unit: 'mg/dL', normalRange: '7 - 20' },
        { name: 'Creatinine', unit: 'mg/dL', normalRange: '0.7 - 1.3' },
        { name: 'eGFR', unit: 'mL/min/1.73m²', normalRange: '> 60' },
        { name: 'Sodium', unit: 'mmol/L', normalRange: '136 - 145' },
        { name: 'Potassium', unit: 'mmol/L', normalRange: '3.5 - 5.1' },
        { name: 'ALT (SGPT)', unit: 'U/L', normalRange: '9 - 46' },
        { name: 'AST (SGOT)', unit: 'U/L', normalRange: '10 - 40' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-4',
      labId: 'lab-1',
      name: 'HbA1c & Glycated Hemoglobin with Average Glucose',
      code: 'GLY-A1C-01',
      category: 'Endocrinology & Diabetes',
      sampleType: 'Whole Blood EDTA',
      turnaroundHours: 8,
      price: 45.0,
      discountPrice: 35.0,
      preparationInstructions: 'No fasting required. Can be done anytime of the day.',
      description: 'Gold-standard monitoring tool reflecting average blood glucose levels over the prior 2 to 3 months.',
      parametersJson: JSON.stringify([
        { name: 'Hemoglobin A1c (HbA1c)', unit: '%', normalRange: '< 5.7 (Normal), 5.7-6.4 (Prediabetes)' },
        { name: 'Estimated Average Glucose (eAG)', unit: 'mg/dL', normalRange: '97 - 126' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-5',
      labId: 'lab-2',
      name: 'Comprehensive Thyroid Function Profile (TSH, FT3, FT4)',
      code: 'THY-PRF-02',
      category: 'Endocrinology & Thyroid',
      sampleType: 'Serum (Blood)',
      turnaroundHours: 24,
      price: 90.0,
      discountPrice: 75.0,
      preparationInstructions: 'Morning sample preferred before taking daily thyroid medication if applicable.',
      description: 'Complete hormone evaluation of pituitary-thyroid axis functionality.',
      parametersJson: JSON.stringify([
        { name: 'TSH (Ultrasensitive)', unit: 'uIU/mL', normalRange: '0.45 - 4.50' },
        { name: 'Free T4 (Thyroxine)', unit: 'ng/dL', normalRange: '0.82 - 1.77' },
        { name: 'Free T3 (Triiodothyronine)', unit: 'pg/mL', normalRange: '2.0 - 4.4' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const appointments: Appointment[] = [
    {
      id: 'apt-1',
      appointmentNumber: 'APT-2026-1001',
      patientId: 'pat-prof-1',
      doctorId: 'doc-prof-1',
      clinicId: 'cln-1',
      date: todayStr,
      timeSlot: '09:30 AM',
      type: 'IN_PERSON',
      status: 'CONFIRMED',
      symptoms: 'Mild chest tightness on exertion and follow-up on recent lipid panel results.',
      notes: 'Patient advised to bring previous laboratory reports.',
      feePaid: 120.0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'apt-2',
      appointmentNumber: 'APT-2026-0988',
      patientId: 'pat-prof-1',
      doctorId: 'doc-prof-3',
      clinicId: 'cln-1',
      date: '2026-10-10',
      timeSlot: '11:00 AM',
      type: 'TELECONSULT',
      status: 'CONFIRMED',
      symptoms: 'Quarterly review of metabolic markers & diet optimization plan.',
      notes: 'Teleconsultation link will be activated 10 minutes prior.',
      feePaid: 110.0,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const queues: Queue[] = [
    {
      id: 'que-1',
      doctorId: 'doc-prof-1',
      clinicId: 'cln-1',
      date: todayStr,
      currentTokenNumber: 3,
      status: 'ACTIVE',
      averageConsultationMin: 18,
      delayMinutes: 5,
      updatedAt: now,
    }
  ];

  const queueTickets: QueueTicket[] = [
    {
      id: 'qtk-1',
      queueId: 'que-1',
      appointmentId: 'apt-1',
      patientId: 'pat-prof-1',
      tokenNumber: 4,
      estimatedTime: '10:15 AM',
      status: 'WAITING',
      checkInTime: now,
    },
    {
      id: 'qtk-prev-1',
      queueId: 'que-1',
      appointmentId: 'apt-mock-demo-1',
      patientId: 'pat-mock-1',
      tokenNumber: 1,
      estimatedTime: '09:00 AM',
      status: 'COMPLETED',
      checkInTime: now,
      calledTime: now,
      completedTime: now,
    },
    {
      id: 'qtk-prev-2',
      queueId: 'que-1',
      appointmentId: 'apt-mock-demo-2',
      patientId: 'pat-mock-2',
      tokenNumber: 2,
      estimatedTime: '09:20 AM',
      status: 'COMPLETED',
      checkInTime: now,
      calledTime: now,
      completedTime: now,
    },
    {
      id: 'qtk-current-3',
      queueId: 'que-1',
      appointmentId: 'apt-mock-demo-3',
      patientId: 'pat-mock-3',
      tokenNumber: 3,
      estimatedTime: '09:45 AM',
      status: 'IN_CONSULTATION',
      checkInTime: now,
      calledTime: now,
    }
  ];

  const referrals: Referral[] = [
    {
      id: 'ref-1',
      referralCode: 'REF-CARD-2026-081',
      doctorId: 'doc-prof-1',
      patientId: 'pat-prof-1',
      labId: 'lab-1',
      testId: 'test-1',
      notes: 'Recommend Advanced Lipid & Cardiovascular Panel with hs-CRP prior to titration of atorvastatin therapy.',
      priority: 'NORMAL',
      status: 'BOOKED',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const testBookings: TestBooking[] = [
    {
      id: 'tb-1',
      bookingNumber: 'TB-2026-4401',
      patientId: 'pat-prof-1',
      labId: 'lab-1',
      testId: 'test-1',
      referralId: 'ref-1',
      collectionType: 'WALK_IN',
      scheduledDate: todayStr,
      scheduledTimeSlot: '08:30 AM',
      collectionAddress: '220 Tech Park Blvd, Bldg C, Portland, OR',
      status: 'SAMPLE_COLLECTED',
      totalAmount: 65.0,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const samples: Sample[] = [
    {
      id: 'smp-1',
      testBookingId: 'tb-1',
      barcode: 'SMP-BC-908123-PL',
      sampleType: 'Serum (Venous Blood, Gold SST Tube)',
      collectedAt: now,
      collectedBy: 'Nurse R. Miller, Phlebotomy Specialist',
      status: 'ANALYZING',
      temperature: '4°C Controlled',
      updatedAt: now,
    }
  ];

  const medicalReports: MedicalReport[] = [
    {
      id: 'rep-1',
      testBookingId: 'tb-1',
      patientId: 'pat-prof-1',
      labId: 'lab-1',
      doctorId: 'doc-prof-1',
      reportTitle: 'Advanced Lipid & Cardiovascular Biomarkers Panel',
      testCategory: 'Cardiology',
      fileUrl: '/uploads/sample_cardiac_lipid_report.pdf',
      fileName: 'Lipid_Cardio_Report_JMiller_2026.pdf',
      fileSize: 245800,
      mimeType: 'application/pdf',
      summary: 'Total Cholesterol and LDL-C are elevated above standard optimal boundaries. High-sensitivity CRP indicates moderate vascular inflammation. HDL level remains protective.',
      extractedFactsJson: JSON.stringify([
        { parameter: 'Total Cholesterol', value: '238', unit: 'mg/dL', referenceRange: '125 - 200', flag: 'HIGH' },
        { parameter: 'HDL Cholesterol', value: '54', unit: 'mg/dL', referenceRange: '> 40', flag: 'NORMAL' },
        { parameter: 'LDL Cholesterol (Calculated)', value: '154', unit: 'mg/dL', referenceRange: '< 100', flag: 'HIGH' },
        { parameter: 'Triglycerides', value: '152', unit: 'mg/dL', referenceRange: '< 150', flag: 'BORDERLINE HIGH' },
        { parameter: 'hs-CRP (Cardiac Risk)', value: '2.8', unit: 'mg/L', referenceRange: '< 1.0', flag: 'HIGH' }
      ]),
      aiAnalysisJson: JSON.stringify({
        summary: 'The laboratory report reveals elevated low-density lipoprotein (LDL) cholesterol at 154 mg/dL along with elevated hs-CRP at 2.8 mg/L. HDL protective cholesterol is at a healthy 54 mg/dL.',
        abnormalFindings: [
          'LDL Cholesterol of 154 mg/dL exceeds normal reference (<100 mg/dL).',
          'hs-CRP of 2.8 mg/L indicates moderate chronic vascular inflammation.',
          'Triglycerides slightly above optimal threshold (152 mg/dL vs <150 mg/dL).'
        ],
        possibleGeneralMeanings: 'Elevated LDL combined with higher hs-CRP is often associated with early atherosclerotic cardiovascular risk. These markers frequently warrant clinical assessment regarding lifestyle, dietary adjustments, and possible lipid-lowering medical management.',
        relevantSpecialties: ['Cardiology', 'Internal Medicine', 'Preventive Health'],
        suggestedQuestionsForDoctor: [
          'What is my estimated 10-year cardiovascular risk score based on these numbers?',
          'Should I begin or modify medication (e.g. statin therapy) or start with targeted nutrition and exercise?',
          'How frequently should my lipid profile and hs-CRP be rechecked?'
        ],
        disclaimer: 'AI-generated information is for educational and healthcare-navigation purposes only. It is not a diagnosis or a substitute for professional medical advice.'
      }),
      status: 'PUBLISHED',
      publishedAt: now,
      isSharedWithDoctor: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const reviews: Review[] = [
    {
      id: 'rev-1',
      patientId: 'pat-prof-1',
      targetType: 'DOCTOR',
      targetId: 'doc-prof-1',
      rating: 5,
      comment: 'Dr. Jenkins took the time to explain every single indicator on my lipid panel. Very reassuring and deeply knowledgeable.',
      isVerifiedVisit: true,
      createdAt: now,
    },
    {
      id: 'rev-2',
      patientId: 'pat-prof-1',
      targetType: 'LABORATORY',
      targetId: 'lab-1',
      rating: 5,
      comment: 'Fast blood draw with zero pain! Results were ready in less than 12 hours with SMS alerts.',
      isVerifiedVisit: true,
      createdAt: now,
    }
  ];

  const notifications: Notification[] = [
    {
      id: 'notif-1',
      userId: 'usr-pat-1',
      title: 'Appointment Confirmed',
      message: 'Your cardiology appointment with Dr. Sarah Jenkins is scheduled for today at 09:30 AM.',
      type: 'APPOINTMENT',
      link: '/patient/appointments',
      isRead: false,
      createdAt: now,
    },
    {
      id: 'notif-2',
      userId: 'usr-pat-1',
      title: 'Live Queue Ticket Issued',
      message: 'You have been assigned Token #4 for Dr. Sarah Jenkins. Estimated call time: 10:15 AM.',
      type: 'QUEUE',
      link: '/patient/appointments',
      isRead: false,
      createdAt: now,
    },
    {
      id: 'notif-3',
      userId: 'usr-pat-1',
      title: 'Diagnostic Sample in Analysis',
      message: 'Sample Barcode SMP-BC-908123-PL has arrived at Precision Diagnostics and is undergoing automated analysis.',
      type: 'SAMPLE',
      link: '/patient/lab-bookings',
      isRead: false,
      createdAt: now,
    },
    {
      id: 'notif-4',
      userId: 'usr-doc-1',
      title: 'Patient Queue Active',
      message: 'Today\'s clinical queue is active with 4 patients scheduled. Current patient in room: Token #3.',
      type: 'QUEUE',
      link: '/doctor/queue',
      isRead: false,
      createdAt: now,
    }
  ];

  const auditLogs: AuditLog[] = [
    {
      id: 'aud-1',
      userId: 'usr-admin-1',
      action: 'SYSTEM_BOOTSTRAP',
      resourceType: 'PLATFORM',
      resourceId: 'MEDILINK-CORE',
      ipAddress: '127.0.0.1',
      userAgent: 'Server-Init/1.0',
      detailsJson: JSON.stringify({ message: 'MediLink Healthcare Ecosystem initialized with verified demo entities.' }),
      createdAt: now,
    }
  ];

  return {
    users,
    patientProfiles,
    doctorProfiles,
    clinics,
    clinicDoctors,
    laboratories,
    diagnosticTests,
    appointments,
    queues,
    queueTickets,
    referrals,
    testBookings,
    samples,
    medicalReports,
    reviews,
    notifications,
    auditLogs
  };
}
