import bcrypt from 'bcryptjs';
import {
  User,
  PatientProfile,
  DoctorProfile,
  Clinic,
  ClinicDoctor,
  Laboratory,
  DiagnosticTest,
  Appointment,
  Queue,
  QueueTicket,
  Referral,
  TestBooking,
  Sample,
  MedicalReport,
  Review,
  Notification,
  AuditLog
} from '../types/index.js';

export function getInitialSeedData() {
  const now = new Date().toISOString();
  const todayStr = now.split('T')[0];

  const salt = bcrypt.genSaltSync(10);
  const passwordPatient = bcrypt.hashSync('Patient@123', salt);
  const passwordDoctor = bcrypt.hashSync('Doctor@123', salt);
  const passwordClinic = bcrypt.hashSync('Clinic@123', salt);
  const passwordLab = bcrypt.hashSync('Lab@123', salt);
  const passwordAdmin = bcrypt.hashSync('Admin@123', salt);

  const users: User[] = [
    {
      id: 'usr-admin-1',
      email: 'admin@medilink.com',
      passwordHash: passwordAdmin,
      name: 'MediLink Lucknow Admin',
      role: 'ADMIN',
      phone: '+91 522 220 9001',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-pat-1',
      email: 'patient@medilink.com',
      passwordHash: passwordPatient,
      name: 'Rahul Sharma',
      role: 'PATIENT',
      phone: '+91 98765 43210',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-1',
      email: 'doctor@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Ananya Srivastava, MD, DM',
      role: 'DOCTOR',
      phone: '+91 94150 12890',
      avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-2',
      email: 'rajeshwar.verma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rajeshwar Verma, MS, MCh',
      role: 'DOCTOR',
      phone: '+91 98390 44521',
      avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-3',
      email: 'priya.mehrotra@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Priya Mehrotra, MD (Endo)',
      role: 'DOCTOR',
      phone: '+91 97210 88200',
      avatarUrl: 'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-4',
      email: 'manish.verma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Manish Verma, MD, DM',
      role: 'DOCTOR',
      phone: '+91 94150 33410',
      avatarUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-5',
      email: 'sunita.chandra@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Sunita Chandra, MS, FICOG',
      role: 'DOCTOR',
      phone: '+91 98391 77620',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-6',
      email: 'rishi.sethi@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rishi Sethi, MD, DM (Cardio)',
      role: 'DOCTOR',
      phone: '+91 94500 88120',
      avatarUrl: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-7',
      email: 'sandeep.kapoor@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Sandeep Kapoor, MS (Ortho)',
      role: 'DOCTOR',
      phone: '+91 98390 11990',
      avatarUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-8',
      email: 'rashmi.kumar@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rashmi Kumar, MD, FAMS',
      role: 'DOCTOR',
      phone: '+91 94150 99400',
      avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-9',
      email: 'rakesh.tandon@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rakesh Tandon, MD, DM (Gastro)',
      role: 'DOCTOR',
      phone: '+91 97210 55110',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-10',
      email: 'neha.rastogi@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Neha Rastogi, MD (Derm)',
      role: 'DOCTOR',
      phone: '+91 98392 44330',
      avatarUrl: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-11',
      email: 'ajay.verma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Ajay Verma, MD, DNB (Pulmo)',
      role: 'DOCTOR',
      phone: '+91 94151 22880',
      avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-12',
      email: 'amit.agarwal@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Amit Agarwal, MS (ENT)',
      role: 'DOCTOR',
      phone: '+91 98390 66770',
      avatarUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-13',
      email: 'sanjeev.mehrotra@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Sanjeev Mehrotra, MS (Ophth)',
      role: 'DOCTOR',
      phone: '+91 98393 11200',
      avatarUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-14',
      email: 'neha.agarwal@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Neha Agarwal, MD, DM (Nephro)',
      role: 'DOCTOR',
      phone: '+91 97211 44550',
      avatarUrl: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-15',
      email: 'vikram.singh@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Vikram Pratap Singh, MCh (Onco)',
      role: 'DOCTOR',
      phone: '+91 94152 77880',
      avatarUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-16',
      email: 'pooja.srivastava@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Pooja Srivastava, MD (Psych)',
      role: 'DOCTOR',
      phone: '+91 98394 55660',
      avatarUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-17',
      email: 'deepak.agarwal@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Deepak Agarwal, MS, MCh (Uro)',
      role: 'DOCTOR',
      phone: '+91 94501 33220',
      avatarUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-18',
      email: 'archana.dixit@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Archana Dixit, MD, DNB (Rheuma)',
      role: 'DOCTOR',
      phone: '+91 98395 66770',
      avatarUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-19',
      email: 'pradeep.sharma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Pradeep Sharma, MD (Med)',
      role: 'DOCTOR',
      phone: '+91 97212 99000',
      avatarUrl: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-20',
      email: 'kavita.tandon@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Kavita Tandon, MS (Surgery)',
      role: 'DOCTOR',
      phone: '+91 94153 88110',
      avatarUrl: 'https://images.unsplash.com/photo-1591604466107-ec97de577aff?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-21',
      email: 'saurabh.mishra@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Saurabh Mishra, MD, EDIC',
      role: 'DOCTOR',
      phone: '+91 98396 22330',
      avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-22',
      email: 'meenakshi.joshi@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Meenakshi Joshi, MS, DGO',
      role: 'DOCTOR',
      phone: '+91 97213 66440',
      avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-clinic-1',
      email: 'clinic@medilink.com',
      passwordHash: passwordClinic,
      name: 'Awadh Mediplex & Heart Institute',
      role: 'CLINIC',
      phone: '+91 522 409 1200',
      avatarUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-lab-1',
      email: 'lab@medilink.com',
      passwordHash: passwordLab,
      name: 'Dr. Lal PathLabs National Reference Hub',
      role: 'LABORATORY',
      phone: '+91 522 409 8899',
      avatarUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=400&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const patientProfiles: PatientProfile[] = [
    {
      id: 'pat-prof-1',
      userId: 'usr-pat-1',
      dob: '1989-05-14',
      gender: 'MALE',
      bloodGroup: 'B_POSITIVE',
      address: 'B-4/112, Sector 4, Gomti Nagar, Lucknow',
      emergencyContact: '+91 98765 11223',
      allergies: 'Penicillin (Mild urticaria), Sulfa drugs',
      medicalHistoryJson: JSON.stringify(['Primary Hypertension (Grade 1)', 'Mild Hyperuricemia']),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinics: Clinic[] = [
    {
      id: 'cln-1',
      userId: 'usr-clinic-1',
      name: 'Awadh Mediplex & Heart Institute',
      address: 'TCG 4/4, Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      phone: '+91 522 409 1200',
      email: 'admin@awadhmediplex.com',
      registrationNo: 'UP-LKO-CLINIC-2022-901',
      servicesJson: JSON.stringify(['Interventional Cardiology', 'Digital ECG & 2D Echo', 'Diabetic Care Unit', 'Executive Health Checkups', 'In-house Pharmacy']),
      facilitiesJson: JSON.stringify(['Wheelchair Accessible', 'Emergency Triage', 'NABL Blood Draw Lounge', 'Covered Parking', 'Live Token Screens']),
      openingTime: '08:00',
      closingTime: '21:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 312,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-2',
      userId: 'usr-clinic-1',
      name: 'Hazratganj Specialty Polyclinic & Diagnostics',
      address: '24 Ashok Marg, Near Hazratganj Crossing',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      phone: '+91 522 228 3344',
      email: 'hazratganj@polyclinic.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2021-412',
      servicesJson: JSON.stringify(['Neurology & Stroke Clinic', 'Headache & Migraine Centre', 'Dermatology & Cosmetology', 'Infertility Assessment']),
      facilitiesJson: JSON.stringify(['Central Air Conditioning', 'Neuro Rehab Suite', 'Express Lab Counter', 'Valet Parking', 'Live Queue Display']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 240,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-3',
      userId: 'usr-clinic-1',
      name: 'Kapoorthala Health & Diabetes Care Centre',
      address: 'Plot 18, Sector B, Kapoorthala, Aliganj',
      city: 'Lucknow',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8920,
      longitude: 80.9385,
      phone: '+91 522 237 9900',
      email: 'aliganj@healthcity.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2023-118',
      servicesJson: JSON.stringify(['Endocrinology & Thyroid Care', 'Continuous Glucose Monitoring (CGM)', 'Diet & Lifestyle Counseling', 'Diabetic Foot Clinic']),
      facilitiesJson: JSON.stringify(['Consultation Chambers', 'Pharmacy', 'Diagnostic Collection Point', 'Patient Education Kiosk']),
      openingTime: '08:30',
      closingTime: '19:30',
      isVerified: true,
      rating: 4.9,
      reviewCount: 195,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-4',
      userId: 'usr-clinic-1',
      name: 'Medanta Super Speciality OPD & Medical Centre',
      address: 'Sector A, Pocket 1, Amar Shaheed Path, Golf City',
      city: 'Lucknow',
      area: 'Sushant Golf City & Shaheed Path',
      latitude: 26.7935,
      longitude: 81.0112,
      phone: '+91 522 450 5050',
      email: 'opd@medanta-lucknow.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2020-008',
      servicesJson: JSON.stringify(['Comprehensive Gastroenterology', 'Cardiology OPD', 'Medical Oncology', 'Organ Transplant Follow-up']),
      facilitiesJson: JSON.stringify(['NABH Accredited Complex', 'Advanced Diagnostic Wing', 'Daycare Surgery', 'Ample Basement Parking']),
      openingTime: '08:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 420,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-5',
      userId: 'usr-clinic-1',
      name: 'Apollo Clinic & Joint Care Centre',
      address: 'Sector B, Bargawan, Kanpur Road (Near Phoenix United)',
      city: 'Lucknow',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7885,
      longitude: 80.8920,
      phone: '+91 522 667 7788',
      email: 'alambagh@apolloclinic.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2021-789',
      servicesJson: JSON.stringify(['Orthopaedics & Joint Replacement', 'Sports Injury Clinic', 'Physiotherapy & Ergonomics', 'Diagnostic X-Ray']),
      facilitiesJson: JSON.stringify(['Apollo Standard Hygiene', 'Digital Radiology', 'Physio Gymnasium', 'Direct Lab Counter']),
      openingTime: '08:30',
      closingTime: '20:30',
      isVerified: true,
      rating: 4.8,
      reviewCount: 215,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-6',
      userId: 'usr-clinic-1',
      name: 'Chandan Multispecialty OPD & Diagnostics',
      address: 'Faizabad Road, Near Indira Nagar Metro Station',
      city: 'Lucknow',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8830,
      longitude: 80.9910,
      phone: '+91 522 423 3300',
      email: 'indiranagar@chandan.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2019-332',
      servicesJson: JSON.stringify(['Pulmonology & Allergy Care', 'ENT & Head-Neck Clinic', 'General Medicine', 'Executive Health Checkups']),
      facilitiesJson: JSON.stringify(['NABL Accreditated Labs', 'Spirometry PFT Lab', 'Audio-Speech Therapy', 'Pharmacy']),
      openingTime: '08:00',
      closingTime: '21:00',
      isVerified: true,
      rating: 4.7,
      reviewCount: 280,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-7',
      userId: 'usr-clinic-1',
      name: 'Charak Medical Centre & Child Health',
      address: 'Dubagga Crossing, Hardoi Link Road, Chowk',
      city: 'Lucknow',
      area: 'Chowk & Old Lucknow',
      latitude: 26.8720,
      longitude: 80.8840,
      phone: '+91 522 241 1234',
      email: 'charak@medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2022-441',
      servicesJson: JSON.stringify(['Pediatrics & Child Vaccination', 'Neonatal Care', 'Cardiology & General Medicine', 'Mother & Child Care']),
      facilitiesJson: JSON.stringify(['Children Play Area', 'Vaccine Cold Chain Facility', 'Pharmacy', 'Emergency Stabilisation']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 165,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-8',
      userId: 'usr-clinic-1',
      name: 'Mahanagar Health Suites & Super Care',
      address: 'Mandir Marg, Near Gole Market, Mahanagar',
      city: 'Lucknow',
      area: 'Mahanagar & Nishatganj',
      latitude: 26.8750,
      longitude: 80.9520,
      phone: '+91 522 233 4455',
      email: 'mahanagar@medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2023-552',
      servicesJson: JSON.stringify(['Obstetrics & Gynaecology', 'Dermatology & Aesthetics', 'Pediatrics', 'Dietetics & Nutrition']),
      facilitiesJson: JSON.stringify(['Private Consultation Suites', 'Ultrasound & Fetal Monitoring', 'Dedicated Daycare', 'Wi-Fi Lounge']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 190,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-9',
      userId: 'usr-clinic-1',
      name: 'Vivekanand Polyclinic & Institute of Medical Sciences',
      address: 'Ramakrishna Mission Marg, Nirala Nagar',
      city: 'Lucknow',
      area: 'Nirala Nagar & Aliganj',
      latitude: 26.8810,
      longitude: 80.9320,
      phone: '+91 522 278 7210',
      email: 'info@vivekanandpolyclinic.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2018-091',
      servicesJson: JSON.stringify(['ENT & Head-Neck Surgery', 'Internal Medicine', 'Ophthalmology', 'Holistic Healthcare']),
      facilitiesJson: JSON.stringify(['Full Service OPD', 'Radiology & CT Scanner', 'Subsidized Medicine Counter', 'Garden Campus']),
      openingTime: '08:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 340,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-10',
      userId: 'usr-clinic-1',
      name: 'Mayo Medical Centre & Super Speciality OPD',
      address: 'Sector 14, Ring Road, Vikas Nagar',
      city: 'Lucknow',
      area: 'Vikas Nagar & Ring Road',
      latitude: 26.8980,
      longitude: 80.9620,
      phone: '+91 522 276 8800',
      email: 'vikasnagar@mayomedical.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2020-562',
      servicesJson: JSON.stringify(['General Medicine & Diabetology', 'Cardiology Consultations', 'Orthopaedics', 'Pediatric Clinic']),
      facilitiesJson: JSON.stringify(['Dedicated OPD Suites', '24x7 Pharmacy', 'Collection Counter', 'Spacious Waiting Lounge']),
      openingTime: '08:30',
      closingTime: '21:00',
      isVerified: true,
      rating: 4.7,
      reviewCount: 220,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-11',
      userId: 'usr-clinic-1',
      name: 'Ajanta Hospital & IVF Fertility Centre',
      address: '765 ABC Complex, Kanpur Road, Alambagh',
      city: 'Lucknow',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7915,
      longitude: 80.8950,
      phone: '+91 522 410 7700',
      email: 'care@ajantahospital.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2019-823',
      servicesJson: JSON.stringify(['Advanced IVF & Infertility', 'High Risk Pregnancy', 'Laparoscopic Gynaecology', 'Fetal Medicine']),
      facilitiesJson: JSON.stringify(['Class 10,000 Cleanroom IVF Lab', 'Advanced USG Doppler', 'Executive Rooms', 'Valet Service']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 275,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-12',
      userId: 'usr-clinic-1',
      name: 'Ford Hospital & Research Centre',
      address: 'Near Shaheed Path Chauraha, Sector 4, Gomti Nagar Extension',
      city: 'Lucknow',
      area: 'Gomti Nagar Extension',
      latitude: 26.8320,
      longitude: 81.0250,
      phone: '+91 522 400 9999',
      email: 'ext@fordhospital.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2021-998',
      servicesJson: JSON.stringify(['Internal Medicine & Critical Care', 'Cardiology & Chest Clinic', 'General Surgery', 'Preventive Health Checks']),
      facilitiesJson: JSON.stringify(['ICU Stepdown Facility', 'NABL Accredited Pathology', 'Emergency Ambulance Point', 'Parking']),
      openingTime: '08:00',
      closingTime: '22:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 310,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-13',
      userId: 'usr-clinic-1',
      name: 'Midland Healthcare & Research Centre',
      address: 'B-55, Mandir Marg, Mahanagar',
      city: 'Lucknow',
      area: 'Mahanagar & Nishatganj',
      latitude: 26.8740,
      longitude: 80.9540,
      phone: '+91 522 404 2222',
      email: 'info@midlandhealthcare.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2020-410',
      servicesJson: JSON.stringify(['Pulmonology & Sleep Lab', 'Cardio-Thoracic Consultations', 'Psychiatry & De-Addiction', 'Neurology']),
      facilitiesJson: JSON.stringify(['NABH Accredited', 'Full Polysomnography Sleep Suite', 'Diagnostic Centre', 'Cafeteria']),
      openingTime: '09:00',
      closingTime: '20:30',
      isVerified: true,
      rating: 4.8,
      reviewCount: 185,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-14',
      userId: 'usr-clinic-1',
      name: 'Regency Super Speciality Clinic',
      address: 'Tedhi Pulia Ring Road, Near Engineering College Chauraha, Kalyanpur',
      city: 'Lucknow',
      area: 'Kalyanpur & Ring Road',
      latitude: 26.9120,
      longitude: 80.9410,
      phone: '+91 522 433 1100',
      email: 'kalyanpur@regencyhealthcare.medilink.com',
      registrationNo: 'UP-LKO-CLINIC-2023-339',
      servicesJson: JSON.stringify(['Super Speciality OPD', 'Urology & Andrology', 'Kidney & Dialysis Consultations', 'Oncology Review']),
      facilitiesJson: JSON.stringify(['Modern Daycare Suite', 'Express Phlebotomy Counter', 'Digital Pharmacy', 'Wheelchair Access']),
      openingTime: '08:30',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 205,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const doctorProfiles: DoctorProfile[] = [
    {
      id: 'doc-prof-1',
      userId: 'usr-doc-1',
      specialty: 'Cardiology',
      subSpecialty: 'Interventional & Preventive Cardiology',
      experienceYears: 16,
      qualification: 'MBBS (KGMU Lucknow), MD (Medicine), DM (Cardiology)',
      licenseNumber: 'UPMC-54210',
      consultationFee: 800.0,
      bio: 'Senior Interventional Cardiologist in Lucknow with over 16 years of clinical excellence. Specializes in preventive cardiology, hypertension control, complex dyslipidemia management, and non-invasive cardiac evaluation.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 220,
      clinicId: 'cln-1',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-2',
      userId: 'usr-doc-2',
      specialty: 'Orthopaedics',
      subSpecialty: 'Joint Replacement (Knee & Hip) & Arthroscopy',
      experienceYears: 18,
      qualification: 'MBBS (KGMU), MS (Orthopaedics), MCh (Ortho - UK)',
      licenseNumber: 'UPMC-48912',
      consultationFee: 850.0,
      bio: 'Renowned orthopaedic and robotic joint replacement surgeon in Lucknow. Expert in minimally invasive hip and knee arthroplasty, sports ligament reconstructions, and chronic osteoarthritis therapy.',
      consultationDuration: 20,
      rating: 4.8,
      reviewCount: 180,
      clinicId: 'cln-1',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-3',
      userId: 'usr-doc-3',
      specialty: 'Endocrinology',
      subSpecialty: 'Type 1 & 2 Diabetes, Thyroid & Metabolic Disorders',
      experienceYears: 11,
      qualification: 'MBBS, MD (Medicine), Fellowship in Clinical Endocrinology (AIIMS)',
      licenseNumber: 'UPMC-61204',
      consultationFee: 700.0,
      bio: 'Expert endocrinologist at Aliganj, Lucknow specializing in insulin pump titration, gestational diabetes, Hashimoto thyroiditis, and obesity-linked metabolic syndrome.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 195,
      clinicId: 'cln-3',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8920,
      longitude: 80.9385,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-4',
      userId: 'usr-doc-4',
      specialty: 'Neurology',
      subSpecialty: 'Stroke, Epilepsy, Migraine & Neuropathy',
      experienceYears: 15,
      qualification: 'MBBS (KGMU), MD (Medicine), DM (Neurology)',
      licenseNumber: 'UPMC-49210',
      consultationFee: 900.0,
      bio: 'Senior consultant neurologist at Hazratganj and Chandan Hospital. Renowned for management of intractable headaches, Parkinson disease, acute ischemic stroke thrombolysis, and peripheral neuropathy.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 240,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-5',
      userId: 'usr-doc-5',
      specialty: 'Gynaecology & Obstetrics',
      subSpecialty: 'High-Risk Pregnancy, Infertility & Laparoscopy',
      experienceYears: 20,
      qualification: 'MBBS, MS (Obstetrics & Gynaecology), FICOG, FICS',
      licenseNumber: 'UPMC-38910',
      consultationFee: 800.0,
      bio: 'Distinguished gynaecologist and obstetrician in Hazratganj and Mahanagar. Over two decades of expertise in high-risk obstetrics, recurrent pregnancy loss, adolescent PCOS, and painless normal deliveries.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 310,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-6',
      userId: 'usr-doc-6',
      specialty: 'Cardiology',
      subSpecialty: 'Complex Coronary Interventions & Structural Heart Care',
      experienceYears: 22,
      qualification: 'MBBS (KGMU), MD (Medicine), DM (Cardiology - SGPGI)',
      licenseNumber: 'UPMC-32104',
      consultationFee: 1000.0,
      bio: 'Senior cardiologist with leadership at KGMU cardiology corridor. Pioneer in radial angiography, primary angioplasty, transcatheter aortic valve implantations, and chronic heart failure regimens.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 450,
      clinicId: 'cln-7',
      area: 'Chowk & Old Lucknow',
      latitude: 26.8720,
      longitude: 80.8840,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-7',
      userId: 'usr-doc-7',
      specialty: 'Orthopaedics',
      subSpecialty: 'Trauma Reconstructions, Spine Decompression & Pelvic Fixation',
      experienceYears: 19,
      qualification: 'MBBS, MS (Orthopaedics), Fellowship Joint Arthroplasty (Singapore)',
      licenseNumber: 'UPMC-44589',
      consultationFee: 800.0,
      bio: 'Chief of orthopaedics and musculoskeletal trauma. Special interest in revision hip replacements, lumbar disc herniations, and geriatric fracture stabilization.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 230,
      clinicId: 'cln-5',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7885,
      longitude: 80.8920,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-8',
      userId: 'usr-doc-8',
      specialty: 'Pediatrics',
      subSpecialty: 'Pediatric Neurology, Developmental Milestones & Immunization',
      experienceYears: 25,
      qualification: 'MBBS, MD (Pediatrics), FAMS, FIAP',
      licenseNumber: 'UPMC-29801',
      consultationFee: 800.0,
      bio: 'Eminent pediatric expert in Lucknow with academic tenure at KGMU. Compassionate clinician specialized in pediatric seizure syndromes, cerebral palsy early intervention, and childhood infections.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 380,
      clinicId: 'cln-8',
      area: 'Mahanagar & Nishatganj',
      latitude: 26.8750,
      longitude: 80.9520,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-9',
      userId: 'usr-doc-9',
      specialty: 'Gastroenterology',
      subSpecialty: 'Hepatology, Therapeutic Endoscopy & IBD',
      experienceYears: 17,
      qualification: 'MBBS, MD (Medicine), DM (Gastroenterology - SGPGI)',
      licenseNumber: 'UPMC-46720',
      consultationFee: 900.0,
      bio: 'Leading gastroenterologist and hepatologist at Medanta Super Speciality Centre. Specialized in fatty liver disease, GERD, chronic hepatitis B/C, ulcerative colitis, and therapeutic ERCP.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 270,
      clinicId: 'cln-4',
      area: 'Sushant Golf City & Shaheed Path',
      latitude: 26.7935,
      longitude: 81.0112,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-10',
      userId: 'usr-doc-10',
      specialty: 'Dermatology',
      subSpecialty: 'Clinical Dermatology, Psoriasis, Acne & Laser Surgery',
      experienceYears: 10,
      qualification: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
      licenseNumber: 'UPMC-63412',
      consultationFee: 650.0,
      bio: 'Leading dermatologist in Central Lucknow specializing in chronic eczema, vitiligo phototherapy, stubborn adult acne, fungal dermatoses, and anti-aging aesthetic procedures.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 160,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-11',
      userId: 'usr-doc-11',
      specialty: 'Pulmonology',
      subSpecialty: 'Asthma, COPD, Interstitial Lung Disease & Sleep Apnea',
      experienceYears: 13,
      qualification: 'MBBS, MD (Pulmonary Medicine), DNB, FCCP',
      licenseNumber: 'UPMC-52119',
      consultationFee: 700.0,
      bio: 'Consultant chest physician at Chandan Hospital, Faizabad Road. Proficient in digital bronchosopy, allergic bronchopulmonary aspergillosis, post-COVID lung fibrosis, and sleep-disordered breathing.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 145,
      clinicId: 'cln-6',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8830,
      longitude: 80.9910,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Wednesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-12',
      userId: 'usr-doc-12',
      specialty: 'ENT',
      subSpecialty: 'Endoscopic Sinus Surgery, Micro-Ear Surgery & Vertigo',
      experienceYears: 12,
      qualification: 'MBBS, MS (Otorhinolaryngology)',
      licenseNumber: 'UPMC-57890',
      consultationFee: 600.0,
      bio: 'ENT specialist at Indira Nagar and Faizabad Road corridor. Dedicated practice in chronic sinusitis, allergic rhinitis, eardrum perforation repair (tympanoplasty), and vestibular vertigo management.',
      consultationDuration: 15,
      rating: 4.7,
      reviewCount: 130,
      clinicId: 'cln-6',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8830,
      longitude: 80.9910,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-13',
      userId: 'usr-doc-13',
      specialty: 'Ophthalmology',
      subSpecialty: 'Micro-Incision Cataract (Phaco), Medical Retina & Glaucoma',
      experienceYears: 15,
      qualification: 'MBBS (KGMU), MS (Ophthalmology), Fellowship Retina (LVPEI)',
      licenseNumber: 'UPMC-50114',
      consultationFee: 650.0,
      bio: 'Distinguished eye surgeon in Gomti Nagar. Expert in premium multifocal and toric IOL implantation, diabetic retinopathy laser photocoagulation, and optical coherence tomography (OCT) diagnostics.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 210,
      clinicId: 'cln-1',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-14',
      userId: 'usr-doc-14',
      specialty: 'Nephrology',
      subSpecialty: 'Chronic Kidney Disease (CKD), Dialysis & Renal Transplantation',
      experienceYears: 14,
      qualification: 'MBBS, MD (Medicine), DM (Nephrology - SGPGI)',
      licenseNumber: 'UPMC-51880',
      consultationFee: 900.0,
      bio: 'Senior nephrologist associated with SGPGI corridor and Medanta Lucknow. Specializes in diabetic nephropathy retardation, maintenance hemodialysis adequacy, glomerulonephritis, and post-transplant immunosuppression.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 185,
      clinicId: 'cln-4',
      area: 'Sushant Golf City & Shaheed Path',
      latitude: 26.7935,
      longitude: 81.0112,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-15',
      userId: 'usr-doc-15',
      specialty: 'Oncology',
      subSpecialty: 'Surgical Oncology, Breast & Gastrointestinal Cancer',
      experienceYears: 17,
      qualification: 'MBBS (KGMU), MS (General Surgery), MCh (Surgical Oncology - TMH Mumbai)',
      licenseNumber: 'UPMC-43920',
      consultationFee: 1000.0,
      bio: 'Consultant surgical oncologist in Lucknow with Tata Memorial Hospital training. Specializes in organ-preserving cancer resections, sentinel lymph node biopsies, and multimodal oncology navigation.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 310,
      clinicId: 'cln-12',
      area: 'Gomti Nagar Extension',
      latitude: 26.8320,
      longitude: 81.0250,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-16',
      userId: 'usr-doc-16',
      specialty: 'Psychiatry',
      subSpecialty: 'Anxiety, Depression, De-addiction & Adult ADHD',
      experienceYears: 11,
      qualification: 'MBBS, MD (Psychiatry - CIP Ranchi)',
      licenseNumber: 'UPMC-62310',
      consultationFee: 750.0,
      bio: 'Compassionate psychiatrist at Mahanagar Mind Care and Midland Healthcare. Dedicated practice in cognitive behavioral approaches, generalized anxiety, bipolar spectrum disorder, and sleep disorders.',
      consultationDuration: 25,
      rating: 4.8,
      reviewCount: 175,
      clinicId: 'cln-8',
      area: 'Mahanagar & Nishatganj',
      latitude: 26.8750,
      longitude: 80.9520,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-17',
      userId: 'usr-doc-17',
      specialty: 'Urology',
      subSpecialty: 'Laser Kidney Stone Removal (RIRS/PCNL) & Prostate Surgery',
      experienceYears: 16,
      qualification: 'MBBS, MS (Surgery), MCh (Urology - KGMU)',
      licenseNumber: 'UPMC-47812',
      consultationFee: 850.0,
      bio: 'Senior urologist and andrologist in South Lucknow. Expert in laser lithotripsy, Holmium laser enucleation of prostate (HoLEP), male fertility evaluations, and urinary tract infections.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 190,
      clinicId: 'cln-5',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7885,
      longitude: 80.8920,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-18',
      userId: 'usr-doc-18',
      specialty: 'Rheumatology',
      subSpecialty: 'Rheumatoid Arthritis, Lupus (SLE), Ankylosing Spondylitis',
      experienceYears: 12,
      qualification: 'MBBS, MD (Medicine), Fellowship in Clinical Rheumatology (CMC Vellore)',
      licenseNumber: 'UPMC-59910',
      consultationFee: 800.0,
      bio: 'Specialist rheumatologist practicing in Central Lucknow. Dedicated care for joint inflammation, biological therapies for autoimmune disorders, osteoporosis, and fibromyalgia management.',
      consultationDuration: 20,
      rating: 4.9,
      reviewCount: 165,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-19',
      userId: 'usr-doc-19',
      specialty: 'General Medicine',
      subSpecialty: 'Internal Medicine, Lifestyle Disease & Geriatric Health',
      experienceYears: 18,
      qualification: 'MBBS, MD (Internal Medicine)',
      licenseNumber: 'UPMC-46102',
      consultationFee: 550.0,
      bio: 'Trusted family physician and general physician at Mayo Medical Centre, Vikas Nagar. Expert management of uncontrolled fevers, hypertension, seasonal dengue/viral illness, and routine senior health checks.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 290,
      clinicId: 'cln-10',
      area: 'Vikas Nagar & Ring Road',
      latitude: 26.8980,
      longitude: 80.9620,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-20',
      userId: 'usr-doc-20',
      specialty: 'General Surgery',
      subSpecialty: 'Laparoscopic Cholecystectomy, Hernia & Anorectal Surgery',
      experienceYears: 14,
      qualification: 'MBBS, MS (General Surgery), FMAS, FIAGES',
      licenseNumber: 'UPMC-53100',
      consultationFee: 700.0,
      bio: 'Experienced minimal access laparoscopic surgeon at Charak Hospital, Chowk. Specialized in laser proctology (piles, fissure, fistula), laparoscopic gallbladder stone removal, and inguinal hernia repairs.',
      consultationDuration: 15,
      rating: 4.7,
      reviewCount: 175,
      clinicId: 'cln-7',
      area: 'Chowk & Old Lucknow',
      latitude: 26.8720,
      longitude: 80.8840,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-21',
      userId: 'usr-doc-21',
      specialty: 'Internal Medicine',
      subSpecialty: 'Critical Care, Sepsis & Infectious Disease',
      experienceYears: 13,
      qualification: 'MBBS, MD (Internal Medicine), European Diploma in Intensive Care (EDIC)',
      licenseNumber: 'UPMC-58204',
      consultationFee: 750.0,
      bio: 'Critical care and acute medicine consultant at Ford Hospital, Gomti Nagar Extension. Expert in multi-organ infection protocols, complex diabetes emergencies, and ICU patient transition care.',
      consultationDuration: 15,
      rating: 4.8,
      reviewCount: 155,
      clinicId: 'cln-12',
      area: 'Gomti Nagar Extension',
      latitude: 26.8320,
      longitude: 81.0250,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-22',
      userId: 'usr-doc-22',
      specialty: 'Gynaecology & Obstetrics',
      subSpecialty: 'High-Risk Pregnancy, Infertility & Minimally Invasive Gynaecology',
      experienceYears: 16,
      qualification: 'MBBS, MS (Obstetrics & Gynaecology), DGO',
      licenseNumber: 'UPMC-49110',
      consultationFee: 750.0,
      bio: 'Senior consultant gynaecologist at Ajanta Hospital, Alambagh. Specializes in advanced maternal-fetal wellness, adolescent hormonal dysfunctions, laparoscopic cystectomy, and natural normal birth coaching.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 260,
      clinicId: 'cln-11',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7915,
      longitude: 80.8950,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinicDoctors: ClinicDoctor[] = [
    { id: 'cln-doc-1', clinicId: 'cln-1', doctorId: 'doc-prof-1', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']), roomNo: 'Room 102 - Cardiology Wing', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-2', clinicId: 'cln-1', doctorId: 'doc-prof-2', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Room 204 - Ortho & Spine Wing', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-3', clinicId: 'cln-3', doctorId: 'doc-prof-3', daysAvailableJson: JSON.stringify(['Tuesday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Chamber 108 - Endocrine Suite', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-4', clinicId: 'cln-2', doctorId: 'doc-prof-4', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Thursday', 'Friday']), roomNo: 'Suite 201 - Neuro Sciences', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-5', clinicId: 'cln-2', doctorId: 'doc-prof-5', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Thursday', 'Saturday']), roomNo: 'Suite 104 - Women Health', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-6', clinicId: 'cln-7', doctorId: 'doc-prof-6', daysAvailableJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']), roomNo: 'Chamber 3 - Cardiac Clinic', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-7', clinicId: 'cln-5', doctorId: 'doc-prof-7', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'OPD 1 - Orthopaedics', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-8', clinicId: 'cln-8', doctorId: 'doc-prof-8', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']), roomNo: 'Suite A - Pediatrics', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-9', clinicId: 'cln-4', doctorId: 'doc-prof-9', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'OPD Block 4 - Gastroenterology', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-10', clinicId: 'cln-2', doctorId: 'doc-prof-10', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']), roomNo: 'Suite 302 - Dermatology', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-11', clinicId: 'cln-6', doctorId: 'doc-prof-11', daysAvailableJson: JSON.stringify(['Tuesday', 'Wednesday', 'Thursday', 'Saturday']), roomNo: 'Room 12 - Chest Medicine', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-12', clinicId: 'cln-6', doctorId: 'doc-prof-12', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Room 8 - ENT OPD', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-13', clinicId: 'cln-1', doctorId: 'doc-prof-13', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']), roomNo: 'Room 105 - Eye Care', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-14', clinicId: 'cln-4', doctorId: 'doc-prof-14', daysAvailableJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']), roomNo: 'OPD Block 2 - Nephrology', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-15', clinicId: 'cln-12', doctorId: 'doc-prof-15', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday']), roomNo: 'Oncology Suite 1', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-16', clinicId: 'cln-8', doctorId: 'doc-prof-16', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']), roomNo: 'Mind Care Room 4', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-17', clinicId: 'cln-5', doctorId: 'doc-prof-17', daysAvailableJson: JSON.stringify(['Tuesday', 'Thursday', 'Saturday']), roomNo: 'OPD 3 - Urology', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-18', clinicId: 'cln-2', doctorId: 'doc-prof-18', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Suite 205 - Rheumatology', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-19', clinicId: 'cln-10', doctorId: 'doc-prof-19', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']), roomNo: 'Room 1 - General Medicine', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-20', clinicId: 'cln-7', doctorId: 'doc-prof-20', daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Friday', 'Saturday']), roomNo: 'Surgical OPD 2', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-21', clinicId: 'cln-12', doctorId: 'doc-prof-21', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']), roomNo: 'Critical Care OPD 3', status: 'ACTIVE', createdAt: now },
    { id: 'cln-doc-22', clinicId: 'cln-11', doctorId: 'doc-prof-22', daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Thursday', 'Friday', 'Saturday']), roomNo: 'Chamber 101 - Women Health', status: 'ACTIVE', createdAt: now }
  ];

  const laboratories: Laboratory[] = [
    {
      id: 'lab-1',
      userId: 'usr-lab-1',
      name: 'Dr. Lal PathLabs National Reference Hub',
      address: '22 Sapru Marg, Near Prem Mandir, Hazratganj',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8490,
      longitude: 80.9480,
      phone: '+91 522 409 8899',
      email: 'lucknow.reference@lalpathlabs.com',
      licenseNo: 'NABL-UP-LAL-2022-881',
      accreditation: 'NABL & CAP Accredited National Reference Lab',
      isVerified: true,
      rating: 4.9,
      reviewCount: 520,
      turnaroundTimeNote: 'Same-day 4-8 hours for all core biochemistry & hematology panels',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-2',
      userId: 'usr-lab-1',
      name: 'Thyrocare Technologies Regional Processing Lab',
      address: 'Shop 4-6, Ground Floor, Kapoorthala Shopping Complex, Aliganj',
      city: 'Lucknow',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8910,
      longitude: 80.9390,
      phone: '+91 522 237 4411',
      email: 'aliganj@thyrocare.com',
      licenseNo: 'NABL-UP-THY-2021-309',
      accreditation: 'NABL & ICMR Certified Fully Automated Track System',
      isVerified: true,
      rating: 4.8,
      reviewCount: 410,
      turnaroundTimeNote: '6-12 hours digital report with automated SMS download link',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-3',
      userId: 'usr-lab-1',
      name: 'Agilus Diagnostics (Formerly SRL Diagnostics)',
      address: 'Plot 14, Rana Pratap Marg, Near Dainik Jagran Chauraha',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8520,
      longitude: 80.9420,
      phone: '+91 522 405 6789',
      email: 'care.lucknow@agilus.in',
      licenseNo: 'NABL-UP-AGI-2020-512',
      accreditation: 'NABL Accredited & Dual International Quality Certified',
      isVerified: true,
      rating: 4.9,
      reviewCount: 390,
      turnaroundTimeNote: '6-8 hours guaranteed TAT for routine blood & viral assays',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-4',
      userId: 'usr-lab-1',
      name: 'Chandan Diagnostic Centre & Imaging Hub',
      address: '15/2, Faizabad Road, Opposite Indira Nagar Metro Station',
      city: 'Lucknow',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8835,
      longitude: 80.9920,
      phone: '+91 522 423 3333',
      email: 'diagnostics@chandan.co.in',
      licenseNo: 'NABL-UP-CHN-2019-108',
      accreditation: 'NABL, NABH & ISO 15189 Quality Certified Medical Laboratory',
      isVerified: true,
      rating: 4.8,
      reviewCount: 460,
      turnaroundTimeNote: '4-8 hours for pathology panels; 12 hours for specialized hormonal assays',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-5',
      userId: 'usr-lab-1',
      name: 'Awadh Diagnostics & Advanced Pathology',
      address: 'TCG 3/3, Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      phone: '+91 522 409 8899',
      email: 'info@awadhdiagnostics.medilink.com',
      licenseNo: 'NABL-UP-AWD-2021-445',
      accreditation: 'NABL Certified Molecular Diagnostic & Flow Cytometry Center',
      isVerified: true,
      rating: 4.8,
      reviewCount: 340,
      turnaroundTimeNote: 'Express 4-6 hours reporting for executive & pre-op health screens',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-6',
      userId: 'usr-lab-1',
      name: 'Medanta Central Pathology & Molecular Genomics',
      address: 'Medanta Complex, Amar Shaheed Path, Golf City',
      city: 'Lucknow',
      area: 'Sushant Golf City & Shaheed Path',
      latitude: 26.7935,
      longitude: 81.0112,
      phone: '+91 522 450 5000',
      email: 'pathology@medanta-lucknow.medilink.com',
      licenseNo: 'NABL-UP-MED-2020-019',
      accreditation: 'NABL & CAP Certified Hospital Reference Laboratory',
      isVerified: true,
      rating: 4.9,
      reviewCount: 480,
      turnaroundTimeNote: 'Same day reporting by specialist MD pathologists',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-7',
      userId: 'usr-lab-1',
      name: 'Metropolis Healthcare South Lucknow Hub',
      address: 'Sector G, Ashiyana, Near Power House Chauraha',
      city: 'Lucknow',
      area: 'Ashiyana & South City',
      latitude: 26.7910,
      longitude: 80.9120,
      phone: '+91 522 411 9900',
      email: 'ashiyana@metropolisindia.com',
      licenseNo: 'NABL-UP-MET-2023-771',
      accreditation: 'NABL & CAP Certified Comprehensive Pathology Network',
      isVerified: true,
      rating: 4.9,
      reviewCount: 310,
      turnaroundTimeNote: 'Same day reporting by senior MD pathologists',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-8',
      userId: 'usr-lab-1',
      name: 'Redcliffe Labs Chowk Diagnostic Centre',
      address: 'Victoria Street, Near Medical College Chauraha, Chowk',
      city: 'Lucknow',
      area: 'Chowk & Old Lucknow',
      latitude: 26.8680,
      longitude: 80.9080,
      phone: '+91 522 350 4400',
      email: 'chowk@redcliffelabs.com',
      licenseNo: 'NABL-UP-RCL-2022-224',
      accreditation: 'NABL Certified Automated Diagnostic Facility',
      isVerified: true,
      rating: 4.8,
      reviewCount: 270,
      turnaroundTimeNote: 'Smart report delivery within 8 hours on WhatsApp & email',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-9',
      userId: 'usr-lab-1',
      name: 'Pathkind Labs Regional Reference Lab',
      address: 'Plot 28, Sector 6, Gomti Nagar Extension',
      city: 'Lucknow',
      area: 'Gomti Nagar Extension',
      latitude: 26.8360,
      longitude: 81.0210,
      phone: '+91 522 490 1100',
      email: 'lucknow.ref@pathkindlabs.com',
      licenseNo: 'NABL-UP-PKL-2021-992',
      accreditation: 'NABL & ISO 15189 Certified Advanced Diagnostic Centre',
      isVerified: true,
      rating: 4.8,
      reviewCount: 290,
      turnaroundTimeNote: '6 to 10 hours for specialized hormonal & oncology markers',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-10',
      userId: 'usr-lab-1',
      name: 'Vijaya Diagnostic Centre & Scans',
      address: 'Phoenix Mall Road, Sector B, Bargawan, Alambagh',
      city: 'Lucknow',
      area: 'Alambagh & Kanpur Road',
      latitude: 26.7890,
      longitude: 80.8930,
      phone: '+91 522 660 8800',
      email: 'alambagh@vijayadiagnostic.com',
      licenseNo: 'NABL-UP-VIJ-2020-331',
      accreditation: 'NABL Certified Integrated Radiology & Pathology Centre',
      isVerified: true,
      rating: 4.8,
      reviewCount: 320,
      turnaroundTimeNote: 'Fast track 4-8 hours for full body blood and urine panels',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-11',
      userId: 'usr-lab-1',
      name: 'Max Lab Collection & Diagnostic Hub',
      address: 'Mayfair Building, Hazratganj Main Market',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8480,
      longitude: 80.9470,
      phone: '+91 522 415 2200',
      email: 'hazratganj@maxlab.co.in',
      licenseNo: 'NABL-UP-MAX-2022-774',
      accreditation: 'NABL & CAP Gold Standard Certified Pathology',
      isVerified: true,
      rating: 4.9,
      reviewCount: 380,
      turnaroundTimeNote: 'Precision robotics processing with real-time temperature tracking',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-12',
      userId: 'usr-lab-1',
      name: 'Tata 1mg Diagnostic & Pathology Lab',
      address: 'B-Block Market, Faizabad Road, Indira Nagar',
      city: 'Lucknow',
      area: 'Indira Nagar & Faizabad Road',
      latitude: 26.8820,
      longitude: 80.9890,
      phone: '+91 522 430 7700',
      email: 'indiranagar@1mgdiagnostics.com',
      licenseNo: 'NABL-UP-1MG-2023-109',
      accreditation: 'NABL Certified Digital Healthcare Network',
      isVerified: true,
      rating: 4.8,
      reviewCount: 340,
      turnaroundTimeNote: 'Digital smart report within 6 hours with free AI doctor consultation',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const diagnosticTests: DiagnosticTest[] = [
    {
      id: 'test-1',
      labId: 'lab-1',
      name: 'Comprehensive Lipid Profile with Cardiac Risk Ratio',
      code: 'LKO-LPD-01',
      category: 'Cardiology & Lipidology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 650.0,
      discountPrice: 499.0,
      preparationInstructions: 'Fasting of 10 to 12 hours is mandatory. Water is permitted.',
      description: 'Measures Total Cholesterol, Direct HDL, Calculated LDL, Triglycerides, VLDL, and Total/HDL Chol Ratio. Essential for heart disease prevention.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol (Direct)', unit: 'mg/dL', normalRange: '> 40 (M), > 50 (F)' },
        { name: 'LDL Cholesterol', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' },
        { name: 'Total Cholesterol / HDL Ratio', unit: 'Ratio', normalRange: '3.0 - 5.0' },
        { name: 'hs-CRP (Cardiac Inflammation)', unit: 'mg/L', normalRange: '< 1.0 (Low Risk)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-2',
      labId: 'lab-2',
      name: 'Standard Lipid Profile Screening',
      code: 'LKO-LPD-02',
      category: 'Cardiology & Lipidology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 500.0,
      discountPrice: 399.0,
      preparationInstructions: 'Strict 10-12 hour fasting required prior to blood draw.',
      description: 'Standard lipid profile test measuring cardiovascular risk factors at Aliganj central lab.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol', unit: 'mg/dL', normalRange: '> 40' },
        { name: 'LDL Cholesterol', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-3',
      labId: 'lab-3',
      name: 'Comprehensive Metabolic & Renal Function Panel (KFT + LFT)',
      code: 'LKO-KFT-LFT-01',
      category: 'Biochemistry & Renal/Hepatic',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 850.0,
      discountPrice: 650.0,
      preparationInstructions: 'Fasting 8-10 hours recommended.',
      description: 'Complete biochemical assessment evaluating kidney parameters (Urea, Creatinine, Uric Acid, eGFR) and liver enzymes (Bilirubin, SGOT, SGPT, Alkaline Phosphatase).',
      parametersJson: JSON.stringify([
        { name: 'Fasting Plasma Glucose', unit: 'mg/dL', normalRange: '70 - 99' },
        { name: 'Blood Urea', unit: 'mg/dL', normalRange: '15 - 40' },
        { name: 'Serum Creatinine', unit: 'mg/dL', normalRange: '0.6 - 1.2' },
        { name: 'Serum Uric Acid', unit: 'mg/dL', normalRange: '3.5 - 7.2' },
        { name: 'Total Bilirubin', unit: 'mg/dL', normalRange: '0.2 - 1.2' },
        { name: 'SGPT (ALT)', unit: 'U/L', normalRange: '0 - 45' },
        { name: 'SGOT (AST)', unit: 'U/L', normalRange: '0 - 40' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-4',
      labId: 'lab-4',
      name: 'Executive KFT with Serum Electrolytes',
      code: 'LKO-KFT-ELE-01',
      category: 'Biochemistry & Renal/Hepatic',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 750.0,
      discountPrice: 550.0,
      preparationInstructions: 'Avoid heavy red meat consumption 24 hours prior.',
      description: 'Renal panel including Urea, BUN, Creatinine, Uric Acid, Sodium, Potassium, Chloride, Calcium.',
      parametersJson: JSON.stringify([
        { name: 'Blood Urea Nitrogen (BUN)', unit: 'mg/dL', normalRange: '7 - 20' },
        { name: 'Serum Creatinine', unit: 'mg/dL', normalRange: '0.7 - 1.3' },
        { name: 'Serum Sodium (Na+)', unit: 'mEq/L', normalRange: '136 - 145' },
        { name: 'Serum Potassium (K+)', unit: 'mEq/L', normalRange: '3.5 - 5.1' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-5',
      labId: 'lab-1',
      name: 'Complete Blood Count (CBC) with Automated 6-Part Differential & ESR',
      code: 'LKO-CBC-01',
      category: 'Hematology',
      sampleType: 'EDTA Whole Blood (Purple Top)',
      turnaroundHours: 4,
      price: 380.0,
      discountPrice: 299.0,
      preparationInstructions: 'No fasting required. Routine venous collection.',
      description: 'Comprehensive blood cell examination detecting anemia, infections, platelet count abnormalities, and inflammatory ESR rate.',
      parametersJson: JSON.stringify([
        { name: 'Hemoglobin', unit: 'g/dL', normalRange: '13.0 - 17.0 (M), 12.0 - 15.0 (F)' },
        { name: 'Total Leukocyte Count (TLC)', unit: '/cumm', normalRange: '4,000 - 10,500' },
        { name: 'Absolute Neutrophil Count', unit: '%', normalRange: '40 - 75' },
        { name: 'Platelet Count', unit: 'Lakh/cumm', normalRange: '1.50 - 4.50' },
        { name: 'Erythrocyte Sedimentation Rate (ESR)', unit: 'mm/1st hr', normalRange: '0 - 15' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-6',
      labId: 'lab-2',
      name: 'CBC (Complete Hemogram) Basic',
      code: 'LKO-CBC-02',
      category: 'Hematology',
      sampleType: 'EDTA Whole Blood',
      turnaroundHours: 6,
      price: 320.0,
      discountPrice: 250.0,
      preparationInstructions: 'No fasting needed.',
      description: 'Routine blood count covering Hemoglobin, RBC, WBC, and Platelet levels.',
      parametersJson: JSON.stringify([
        { name: 'Hemoglobin', unit: 'g/dL', normalRange: '12.0 - 16.5' },
        { name: 'Total WBC', unit: '/cumm', normalRange: '4,000 - 10,000' },
        { name: 'Platelets', unit: 'Lakh/cumm', normalRange: '1.5 - 4.0' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-7',
      labId: 'lab-3',
      name: 'Glycosylated Hemoglobin (HbA1c) with Estimated Average Glucose (eAG)',
      code: 'LKO-HBA1C-01',
      category: 'Endocrinology & Diabetes',
      sampleType: 'EDTA Whole Blood',
      turnaroundHours: 6,
      price: 550.0,
      discountPrice: 420.0,
      preparationInstructions: 'Non-fasting. Can be done anytime of the day.',
      description: 'Gold-standard HPLC test determining mean blood glucose control over past 90 days. Crucial for diabetes screening and insulin titration.',
      parametersJson: JSON.stringify([
        { name: 'HbA1c (Glycosylated Hb)', unit: '%', normalRange: '< 5.7 (Normal), 5.7-6.4 (Prediabetes), >= 6.5 (Diabetes)' },
        { name: 'Estimated Average Glucose (eAG)', unit: 'mg/dL', normalRange: '< 117' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-8',
      labId: 'lab-2',
      name: 'HbA1c Monitoring Assay',
      code: 'LKO-HBA1C-02',
      category: 'Endocrinology & Diabetes',
      sampleType: 'EDTA Whole Blood',
      turnaroundHours: 8,
      price: 450.0,
      discountPrice: 350.0,
      preparationInstructions: 'No preparation needed.',
      description: 'Quarterly diabetic blood sugar management assessment.',
      parametersJson: JSON.stringify([
        { name: 'HbA1c', unit: '%', normalRange: '< 5.7%' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-9',
      labId: 'lab-1',
      name: 'Comprehensive Thyroid Profile Total (T3, T4, Ultra-sensitive TSH)',
      code: 'LKO-THY-01',
      category: 'Endocrinology & Diabetes',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 500.0,
      discountPrice: 399.0,
      preparationInstructions: 'Early morning fasting sample preferred. Take thyroid meds only after blood collection.',
      description: 'Evaluates thyroid gland physiology, detecting hypothyroidism, hyperthyroidism, Hashimoto thyroiditis, and pituitary axis regulation.',
      parametersJson: JSON.stringify([
        { name: 'Total Triiodothyronine (T3)', unit: 'ng/dL', normalRange: '60 - 200' },
        { name: 'Total Thyroxine (T4)', unit: 'ug/dL', normalRange: '4.5 - 12.0' },
        { name: 'Thyroid Stimulating Hormone (TSH)', unit: 'uIU/mL', normalRange: '0.35 - 4.94' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-10',
      labId: 'lab-4',
      name: 'Free Thyroid Panel (FT3, FT4, Sensitive TSH)',
      code: 'LKO-THY-02',
      category: 'Endocrinology & Diabetes',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 750.0,
      discountPrice: 599.0,
      preparationInstructions: 'Morning sample before breakfast.',
      description: 'Free hormone concentrations providing superior accuracy in pregnancy and metabolic disorders.',
      parametersJson: JSON.stringify([
        { name: 'Free T3', unit: 'pg/mL', normalRange: '2.3 - 4.2' },
        { name: 'Free T4', unit: 'ng/dL', normalRange: '0.8 - 1.8' },
        { name: 'TSH', unit: 'uIU/mL', normalRange: '0.35 - 4.94' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-11',
      labId: 'lab-1',
      name: 'Vitamin D (25-Hydroxy Cholecalciferol) Quantitative CLIA',
      code: 'LKO-VIT-D-01',
      category: 'Vitamins & Bone Health',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 1200.0,
      discountPrice: 899.0,
      preparationInstructions: 'No fasting required. Avoid high-dose vitamin supplements 24h prior.',
      description: 'Assesses active Vitamin D reserves for bone density, immune health, and calcium absorption.',
      parametersJson: JSON.stringify([
        { name: '25-OH Vitamin D Total', unit: 'ng/mL', normalRange: '< 20 (Deficient), 20-30 (Insufficient), 30-100 (Sufficient)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-12',
      labId: 'lab-2',
      name: 'Vitamin B12 (Cyanocobalamin) Assay',
      code: 'LKO-VIT-B12-01',
      category: 'Vitamins & Bone Health',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 900.0,
      discountPrice: 699.0,
      preparationInstructions: 'Fasting 8 hours recommended.',
      description: 'Essential for nerve myelination, cognitive health, and red blood cell production.',
      parametersJson: JSON.stringify([
        { name: 'Vitamin B12', unit: 'pg/mL', normalRange: '211 - 911' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-13',
      labId: 'lab-5',
      name: 'High Sensitivity Cardiac Troponin I (hs-cTnI)',
      code: 'LKO-TROP-I-01',
      category: 'Cardiology & Cardiac Markers',
      sampleType: 'Serum / Heparin Plasma',
      turnaroundHours: 3,
      price: 1400.0,
      discountPrice: 1100.0,
      preparationInstructions: 'STAT test. No preparation required.',
      description: 'Ultra-sensitive biomarker for myocardial necrosis, unstable angina, and acute coronary syndrome.',
      parametersJson: JSON.stringify([
        { name: 'hs-Troponin I', unit: 'ng/L', normalRange: '< 15.6 (M), < 11.6 (F)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-14',
      labId: 'lab-6',
      name: 'D-Dimer Quantitative Assay (Thromboembolism Screen)',
      code: 'LKO-DDIMER-01',
      category: 'Hematology & Coagulation',
      sampleType: 'Citrated Plasma (Blue Top)',
      turnaroundHours: 4,
      price: 1100.0,
      discountPrice: 850.0,
      preparationInstructions: 'Routine venous blood in sodium citrate tube.',
      description: 'Detects intravascular coagulation, deep vein thrombosis (DVT), and pulmonary embolism.',
      parametersJson: JSON.stringify([
        { name: 'D-Dimer', unit: 'ug/mL FEU', normalRange: '< 0.50' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-15',
      labId: 'lab-7',
      name: 'Comprehensive Iron Studies & Serum Ferritin Panel',
      code: 'LKO-IRON-01',
      category: 'Hematology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 1100.0,
      discountPrice: 799.0,
      preparationInstructions: 'Morning fasting blood sample preferred.',
      description: 'Measures Serum Iron, Ferritin, Total Iron Binding Capacity (TIBC), and Transferrin Saturation.',
      parametersJson: JSON.stringify([
        { name: 'Serum Iron', unit: 'ug/dL', normalRange: '65 - 175' },
        { name: 'Serum Ferritin', unit: 'ng/mL', normalRange: '20 - 250 (M), 10 - 120 (F)' },
        { name: 'TIBC', unit: 'ug/dL', normalRange: '250 - 450' },
        { name: 'Transferrin Saturation', unit: '%', normalRange: '20 - 50' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-16',
      labId: 'lab-8',
      name: 'Dengue Serology NS1 Antigen & IgM/IgG Antibodies Combo',
      code: 'LKO-DENGUE-01',
      category: 'Infectious Disease & Serology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 4,
      price: 850.0,
      discountPrice: 650.0,
      preparationInstructions: 'No preparation needed. Rapid emergency reporting.',
      description: 'Triple parameter serological panel detecting acute viral antigen and immune response antibodies for dengue fever.',
      parametersJson: JSON.stringify([
        { name: 'Dengue NS1 Antigen', unit: 'Qualitative', normalRange: 'Negative' },
        { name: 'Dengue IgM Antibodies', unit: 'Index', normalRange: '< 1.0 (Negative)' },
        { name: 'Dengue IgG Antibodies', unit: 'Index', normalRange: '< 1.0 (Negative)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-17',
      labId: 'lab-9',
      name: 'Typhoid Widal Agglutination Slide & Tube Test',
      code: 'LKO-WIDAL-01',
      category: 'Infectious Disease & Serology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 4,
      price: 280.0,
      discountPrice: 200.0,
      preparationInstructions: 'No special instructions.',
      description: 'Detects agglutinating antibodies to Salmonella enterica serotypes Typhi (TO, TH) and Paratyphi (AH, BH).',
      parametersJson: JSON.stringify([
        { name: 'S. Typhi O Antigen', unit: 'Titre', normalRange: '< 1:80' },
        { name: 'S. Typhi H Antigen', unit: 'Titre', normalRange: '< 1:80' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-18',
      labId: 'lab-10',
      name: 'Urine Routine & Microscopic Examination (Urine R/M)',
      code: 'LKO-URINE-01',
      category: 'Clinical Pathology & Urinalysis',
      sampleType: 'Clean Catch Midstream Urine',
      turnaroundHours: 4,
      price: 250.0,
      discountPrice: 180.0,
      preparationInstructions: 'First morning midstream clean-catch sample in sterile container provided.',
      description: 'Physical, chemical, and microscopic examination for proteinuria, hematuria, urinary tract infection, and crystals.',
      parametersJson: JSON.stringify([
        { name: 'Urine Glucose', unit: 'Qualitative', normalRange: 'Nil' },
        { name: 'Urine Protein / Albumin', unit: 'Qualitative', normalRange: 'Nil' },
        { name: 'Pus Cells (Leukocytes)', unit: '/HPF', normalRange: '0 - 5' },
        { name: 'Red Blood Cells (RBCs)', unit: '/HPF', normalRange: '0 - 2' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-19',
      labId: 'lab-11',
      name: 'Total Prostate Specific Antigen (PSA) for Men',
      code: 'LKO-PSA-01',
      category: 'Oncology & Mens Health',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 850.0,
      discountPrice: 650.0,
      preparationInstructions: 'Avoid vigorous bicycling or sexual activity 48 hours prior.',
      description: 'Screening biomarker for benign prostatic hyperplasia (BPH) and prostate carcinoma.',
      parametersJson: JSON.stringify([
        { name: 'Total PSA', unit: 'ng/mL', normalRange: '< 4.0' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-20',
      labId: 'lab-12',
      name: 'Comprehensive Allergy Screen (Food & Environmental Inhalants)',
      code: 'LKO-ALLERGY-01',
      category: 'Immunology & Allergy',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 24,
      price: 3500.0,
      discountPrice: 2800.0,
      preparationInstructions: 'Antihistamines should be discontinued 48 hours before with doctor consent.',
      description: 'Multi-allergen panel testing IgE response to dust mites, pollens, fungi, milk, eggs, nuts, and seafood.',
      parametersJson: JSON.stringify([
        { name: 'Total Serum IgE', unit: 'IU/mL', normalRange: '< 100' },
        { name: 'Inhalant Allergen Panel', unit: 'Class', normalRange: 'Class 0 (Negative)' },
        { name: 'Food Allergen Panel', unit: 'Class', normalRange: 'Class 0 (Negative)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-21',
      labId: 'lab-4',
      name: 'Digital Chest X-Ray PA View (High Resolution)',
      code: 'LKO-XRAY-01',
      category: 'Radiology & Imaging',
      sampleType: 'Radiological Imaging',
      turnaroundHours: 2,
      price: 500.0,
      discountPrice: 380.0,
      preparationInstructions: 'Remove all metallic jewelry and metal fasteners from upper torso.',
      description: 'Low-dose digital radiography of lungs, mediastinum, cardiothoracic ratio, and thoracic skeleton.',
      parametersJson: JSON.stringify([
        { name: 'Lung Fields', unit: 'Visual', normalRange: 'Clear lung parenchymal fields' },
        { name: 'Cardiothoracic Ratio', unit: 'Ratio', normalRange: '< 0.50 (Normal size)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-22',
      labId: 'lab-4',
      name: '12-Lead Digital Electrocardiogram (ECG) with Specialist Review',
      code: 'LKO-ECG-01',
      category: 'Cardiology & Diagnostic Imaging',
      sampleType: 'Electrophysiological Tracing',
      turnaroundHours: 1,
      price: 350.0,
      discountPrice: 250.0,
      preparationInstructions: 'Rest calmly 10 minutes prior. Avoid strenuous walking.',
      description: 'Precision 12-lead electrical recording of cardiac rhythms, conduction delays, and ischemic ST-T changes.',
      parametersJson: JSON.stringify([
        { name: 'Heart Rate', unit: 'bpm', normalRange: '60 - 100' },
        { name: 'Cardiac Rhythm', unit: 'Interpretation', normalRange: 'Normal Sinus Rhythm' },
        { name: 'PR Interval', unit: 'ms', normalRange: '120 - 200' },
        { name: 'QRS Duration', unit: 'ms', normalRange: '< 120' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-23',
      labId: 'lab-5',
      name: 'Ultrasound Whole Abdomen & Pelvis (USG Abdomen)',
      code: 'LKO-USG-01',
      category: 'Radiology & Sonography',
      sampleType: 'Acoustic Sonogram',
      turnaroundHours: 2,
      price: 1200.0,
      discountPrice: 950.0,
      preparationInstructions: 'Overnight fasting of 6-8 hours required. Drink 1 litre of water 1 hour before test for full bladder.',
      description: 'High-definition gray scale and color Doppler sonography of liver, gallbladder, pancreas, spleen, kidneys, urinary bladder, and pelvic organs.',
      parametersJson: JSON.stringify([
        { name: 'Liver Echotexture', unit: 'Visual', normalRange: 'Normal size & homogeneous echotexture' },
        { name: 'Gallbladder & CBD', unit: 'Visual', normalRange: 'Lumen free of calculi, normal wall thickness' },
        { name: 'Kidneys (Bilateral)', unit: 'Visual', normalRange: 'Normal corticomedullary differentiation' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-24',
      labId: 'lab-1',
      name: '2D Echocardiography with Color Doppler (2D Echo)',
      code: 'LKO-ECHO-01',
      category: 'Cardiology & Sonography',
      sampleType: 'Transthoracic Ultrasound',
      turnaroundHours: 2,
      price: 2200.0,
      discountPrice: 1750.0,
      preparationInstructions: 'No fasting required. Wear comfortable two-piece clothing.',
      description: 'Evaluates cardiac chambers, valvular hemodynamics, ejection fraction (LVEF), diastolic function, and pericardium.',
      parametersJson: JSON.stringify([
        { name: 'Left Ventricular Ejection Fraction (LVEF)', unit: '%', normalRange: '55 - 70' },
        { name: 'Valvular Function', unit: 'Doppler', normalRange: 'No hemodynamically significant stenosis or regurgitation' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-25',
      labId: 'lab-3',
      name: 'Hepatitis B Surface Antigen (HBsAg) Quantitative ECLIA',
      code: 'LKO-HBSAG-01',
      category: 'Infectious Disease & Serology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 550.0,
      discountPrice: 420.0,
      preparationInstructions: 'No dietary restrictions.',
      description: 'Chemiluminescence immunoassay detecting active hepatitis B viral infection and carrier status.',
      parametersJson: JSON.stringify([
        { name: 'HBsAg Quantitative', unit: 'COI / Index', normalRange: '< 0.90 (Non-Reactive)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-26',
      labId: 'lab-3',
      name: 'Anti-HCV Total Antibodies (Hepatitis C Screening)',
      code: 'LKO-HCV-01',
      category: 'Infectious Disease & Serology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 750.0,
      discountPrice: 580.0,
      preparationInstructions: 'No preparation required.',
      description: 'Screening assay for exposure to Hepatitis C virus.',
      parametersJson: JSON.stringify([
        { name: 'Anti-HCV Total', unit: 'Signal/Cutoff', normalRange: '< 1.0 (Non-Reactive)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-27',
      labId: 'lab-1',
      name: 'HIV 1 & 2 4th Generation Antigen & Antibody (p24) Combo',
      code: 'LKO-HIV-01',
      category: 'Infectious Disease & Serology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 650.0,
      discountPrice: 499.0,
      preparationInstructions: 'Strictly confidential test. Pre-test consent followed.',
      description: 'Ultra-sensitive 4th gen combo assay detecting HIV p24 antigen and antibodies with reduced window period.',
      parametersJson: JSON.stringify([
        { name: 'HIV 1 & 2 Combo (Ag/Ab)', unit: 'Index', normalRange: '< 0.90 (Non-Reactive)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-28',
      labId: 'lab-2',
      name: 'Fasting Plasma Glucose (FBS) with Post-Prandial (PPBS)',
      code: 'LKO-SUGAR-01',
      category: 'Endocrinology & Diabetes',
      sampleType: 'Fluoride Plasma (Gray Top)',
      turnaroundHours: 4,
      price: 200.0,
      discountPrice: 150.0,
      preparationInstructions: 'FBS: 8-10h overnight fasting. PPBS: Exactly 2 hours after start of standard meal.',
      description: 'Core paired diagnostic test for diabetes diagnosis, glucose tolerance, and dietary glycemic control.',
      parametersJson: JSON.stringify([
        { name: 'Fasting Blood Sugar', unit: 'mg/dL', normalRange: '70 - 99' },
        { name: 'Post-Prandial Blood Sugar (2 hr)', unit: 'mg/dL', normalRange: '< 140' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-29',
      labId: 'lab-7',
      name: 'Serum Uric Acid Quantitative',
      code: 'LKO-URIC-01',
      category: 'Biochemistry & Renal/Hepatic',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 4,
      price: 250.0,
      discountPrice: 180.0,
      preparationInstructions: 'Fasting 4 hours recommended.',
      description: 'Screens for hyperuricemia, gouty arthritis, joint pain, and kidney stone risk.',
      parametersJson: JSON.stringify([
        { name: 'Serum Uric Acid', unit: 'mg/dL', normalRange: '3.5 - 7.2 (M), 2.6 - 6.0 (F)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-30',
      labId: 'lab-6',
      name: 'Serum Prolactin (Hormonal Evaluation)',
      code: 'LKO-PROL-01',
      category: 'Endocrinology & Women Health',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 600.0,
      discountPrice: 450.0,
      preparationInstructions: 'Sample between 8 AM - 10 AM, 2 hours after waking. Avoid physical stress.',
      description: 'Assesses pituitary prolactin secretion for menstrual irregularity, galactorrhea, and infertility.',
      parametersJson: JSON.stringify([
        { name: 'Prolactin', unit: 'ng/mL', normalRange: '4.79 - 23.3 (Female), 4.04 - 15.2 (Male)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-31',
      labId: 'lab-1',
      name: 'High Sensitivity C-Reactive Protein (hs-CRP Quantitative)',
      code: 'LKO-HSCRP-01',
      category: 'Cardiology & Inflammation',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 6,
      price: 550.0,
      discountPrice: 420.0,
      preparationInstructions: 'Patient should be in steady state without acute infection or trauma.',
      description: 'Precise measurement of basal systemic inflammation for cardiovascular atheroma risk profiling.',
      parametersJson: JSON.stringify([
        { name: 'hs-CRP', unit: 'mg/L', normalRange: '< 1.0 (Low Risk), 1.0 - 3.0 (Average Risk), > 3.0 (High Risk)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-32',
      labId: 'lab-5',
      name: 'Prothrombin Time with INR (PT / INR Coagulation Screen)',
      code: 'LKO-PTINR-01',
      category: 'Hematology & Coagulation',
      sampleType: 'Sodium Citrate Whole Blood',
      turnaroundHours: 3,
      price: 400.0,
      discountPrice: 300.0,
      preparationInstructions: 'Routine venous blood. Mention any anticoagulant therapy (Warfarin/Acitrom).',
      description: 'Monitors oral anticoagulant therapy, liver synthetic function, and extrinsic coagulation pathway.',
      parametersJson: JSON.stringify([
        { name: 'Patient Prothrombin Time', unit: 'Seconds', normalRange: '11.0 - 13.5' },
        { name: 'International Normalized Ratio (INR)', unit: 'Ratio', normalRange: '0.85 - 1.15' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const appointments: Appointment[] = [
    {
      id: 'apt-1',
      appointmentNumber: 'APT-LKO-1001',
      patientId: 'pat-prof-1',
      doctorId: 'doc-prof-1',
      clinicId: 'cln-1',
      date: todayStr,
      timeSlot: '10:30',
      status: 'CONFIRMED',
      type: 'IN_PERSON',
      feePaid: 800.0,
      notes: 'Follow-up for blood pressure medication titration and recent lipid review.',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const queues: Queue[] = [
    {
      id: 'que-1',
      clinicId: 'cln-1',
      doctorId: 'doc-prof-1',
      date: todayStr,
      currentTokenNumber: 8,
      status: 'ACTIVE',
      averageConsultationMin: 12,
      delayMinutes: 0,
      updatedAt: now,
    }
  ];

  const queueTickets: QueueTicket[] = [
    {
      id: 'tkt-1',
      queueId: 'que-1',
      appointmentId: 'apt-1',
      patientId: 'pat-prof-1',
      tokenNumber: 9,
      status: 'IN_CONSULTATION',
      estimatedTime: '10:30',
      calledTime: now,
    }
  ];

  const referrals: Referral[] = [];

  const testBookings: TestBooking[] = [
    {
      id: 'tbk-1',
      bookingNumber: 'TBK-LKO-9001',
      patientId: 'pat-prof-1',
      labId: 'lab-1',
      testId: 'test-1',
      scheduledDate: todayStr,
      scheduledTimeSlot: '08:00',
      collectionType: 'HOME_COLLECTION',
      collectionAddress: 'B-4/112, Sector 4, Gomti Nagar, Lucknow',
      status: 'REPORT_READY',
      totalAmount: 499.0,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const samples: Sample[] = [
    {
      id: 'smp-1',
      testBookingId: 'tbk-1',
      barcode: 'LKO-LAL-908122',
      sampleType: 'Serum (Venous Blood)',
      status: 'COMPLETED',
      collectedAt: now,
      updatedAt: now,
    }
  ];

  const medicalReports: MedicalReport[] = [
    {
      id: 'rep-1',
      patientId: 'pat-prof-1',
      testBookingId: 'tbk-1',
      labId: 'lab-1',
      reportTitle: 'Comprehensive Lipid Profile with Cardiac Risk Ratio',
      testCategory: 'Cardiology & Lipidology',
      fileUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=800&q=80',
      fileName: 'lipid_profile_report.pdf',
      fileSize: 245000,
      mimeType: 'application/pdf',
      summary: 'Dyslipidemia detected with elevated total cholesterol (218 mg/dL) and triglycerides (188 mg/dL).',
      extractedFactsJson: JSON.stringify([
        { parameter: 'Total Cholesterol', value: '218', unit: 'mg/dL', normalRange: '125 - 200', interpretation: 'HIGH' },
        { parameter: 'HDL Cholesterol (Protective)', value: '38', unit: 'mg/dL', normalRange: '> 40', interpretation: 'LOW' },
        { parameter: 'Calculated LDL Cholesterol', value: '142', unit: 'mg/dL', normalRange: '< 100', interpretation: 'HIGH' },
        { parameter: 'Triglycerides', value: '188', unit: 'mg/dL', normalRange: '< 150', interpretation: 'HIGH' },
        { parameter: 'Cholesterol / HDL Ratio', value: '5.7', unit: 'Ratio', normalRange: '3.0 - 5.0', interpretation: 'ABNORMAL' }
      ]),
      aiAnalysisJson: JSON.stringify({
        summary: 'Dyslipidemia detected with elevated total cholesterol (218 mg/dL), elevated triglycerides (188 mg/dL), and suboptimal protective HDL (38 mg/dL). These findings suggest moderate atherosclerotic cardiovascular risk requiring dietary fat modification and clinical evaluation.',
        keyFindings: [
          'Total Cholesterol is mildly elevated at 218 mg/dL (optimal < 200 mg/dL).',
          'Triglycerides are elevated at 188 mg/dL reflecting dietary carbohydrate and fat processing.',
          'Cardiovascular risk ratio of 5.7 indicates need for physician consultation.'
        ],
        lifestyleAdvice: [
          'Adopt a heart-healthy diet rich in soluble fiber (oats, fenugreek, flaxseeds).',
          'Reduce saturated fats, vanaspati ghee, and deep-fried savory snacks.',
          'Engage in 30-45 minutes of brisk walking along Gomti Riverfront or residential parks at least 5 days weekly.'
        ],
        matchedSpecialty: 'Cardiology',
        suggestedSpecialists: [
          { name: 'Dr. Ananya Srivastava, MD, DM', specialty: 'Cardiology', clinicName: 'Awadh Mediplex & Heart Institute' },
          { name: 'Dr. Rishi Sethi, MD, DM', specialty: 'Cardiology', clinicName: 'Charak Medical Centre & KGMU Corridor' }
        ]
      }),
      status: 'PUBLISHED',
      isSharedWithDoctor: true,
      publishedAt: now,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const reviews: Review[] = [
    { id: 'rev-1', patientId: 'pat-prof-1', targetType: 'DOCTOR', targetId: 'doc-prof-1', rating: 5, comment: 'Dr. Ananya Srivastava is exceptionally thorough and patient. She explained my cardiac risk score and adjusted my medication without unnecessary tests.', isVerifiedVisit: true, createdAt: now },
    { id: 'rev-2', patientId: 'pat-prof-1', targetType: 'DOCTOR', targetId: 'doc-prof-3', rating: 5, comment: 'Dr. Priya Mehrotra in Kapoorthala is an outstanding endocrinologist! Her guidance on diabetes diet and insulin timing has brought my HbA1c under control.', isVerifiedVisit: true, createdAt: now },
    { id: 'rev-3', patientId: 'pat-prof-1', targetType: 'LABORATORY', targetId: 'lab-1', rating: 5, comment: 'Punctual home sample collection in Gomti Nagar. The phlebotomist arrived right at 7:30 AM with cold transport container. Report was ready by 2 PM.', isVerifiedVisit: true, createdAt: now },
    { id: 'rev-4', patientId: 'pat-prof-1', targetType: 'CLINIC', targetId: 'cln-1', rating: 5, comment: 'Awadh Mediplex in Vibhuti Khand has seamless live token display. No long standing queues in OPD waiting room.', isVerifiedVisit: true, createdAt: now }
  ];

  const notifications: Notification[] = [
    { id: 'notif-1', userId: 'usr-pat-1', title: 'Token #9 is Next in Live Queue', message: 'Dr. Ananya Srivastava is now seeing Token #8. Please be seated near Chamber 102 at Awadh Mediplex.', type: 'QUEUE', isRead: false, link: '/patient/appointments', createdAt: now },
    { id: 'notif-2', userId: 'usr-pat-1', title: 'Diagnostic Report Ready', message: 'Your Comprehensive Lipid Profile report from Dr. Lal PathLabs has been verified by the chief pathologist and analyzed by AI.', type: 'REPORT', isRead: false, link: '/patient/reports', createdAt: now }
  ];

  const auditLogs: AuditLog[] = [
    { id: 'aud-1', userId: 'usr-admin-1', action: 'PROVIDER_VERIFICATION_APPROVED', resourceType: 'DOCTOR_LICENSE', resourceId: 'UPMC-54210', detailsJson: JSON.stringify({ doctor: 'Dr. Ananya Srivastava', status: 'VERIFIED', stateCouncil: 'UP Medical Council' }), ipAddress: '127.0.0.1', userAgent: 'MediLink Internal Audit Engine', createdAt: now },
    { id: 'aud-2', userId: 'usr-admin-1', action: 'LAB_ACCREDITATION_VERIFIED', resourceType: 'NABL_CERTIFICATE', resourceId: 'NABL-UP-LAL-2022-881', detailsJson: JSON.stringify({ lab: 'Dr. Lal PathLabs Reference Hub', accreditation: 'NABL & CAP' }), ipAddress: '127.0.0.1', userAgent: 'MediLink Internal Audit Engine', createdAt: now }
  ];

  return {
    users,
    patientProfiles,
    doctorProfiles,
    clinics,
    clinicDoctors,
    laboratories,
    diagnosticTests,
    appointments,
    queues,
    queueTickets,
    referrals,
    testBookings,
    samples,
    medicalReports,
    reviews,
    notifications,
    auditLogs
  };
}
