import bcrypt from 'bcryptjs';
import {
  User,
  PatientProfile,
  DoctorProfile,
  Clinic,
  ClinicDoctor,
  Laboratory,
  DiagnosticTest,
  Appointment,
  Queue,
  QueueTicket,
  Referral,
  TestBooking,
  Sample,
  MedicalReport,
  Review,
  Notification,
  AuditLog
} from '../types/index.js';

export function getInitialSeedData() {
  const now = new Date().toISOString();
  const todayStr = now.split('T')[0];

  const salt = bcrypt.genSaltSync(10);
  const passwordPatient = bcrypt.hashSync('Patient@123', salt);
  const passwordDoctor = bcrypt.hashSync('Doctor@123', salt);
  const passwordClinic = bcrypt.hashSync('Clinic@123', salt);
  const passwordLab = bcrypt.hashSync('Lab@123', salt);
  const passwordAdmin = bcrypt.hashSync('Admin@123', salt);

  const users: User[] = [
    {
      id: 'usr-admin-1',
      email: 'admin@medilink.com',
      passwordHash: passwordAdmin,
      name: 'MediLink Lucknow Admin',
      role: 'ADMIN',
      phone: '+91 522 220 9001',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-pat-1',
      email: 'patient@medilink.com',
      passwordHash: passwordPatient,
      name: 'Rahul Sharma',
      role: 'PATIENT',
      phone: '+91 98765 43210',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-1',
      email: 'doctor@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Ananya Srivastava, MD, DM',
      role: 'DOCTOR',
      phone: '+91 94150 12890',
      avatarUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-2',
      email: 'rajeshwar.verma@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Rajeshwar Verma, MS, MCh',
      role: 'DOCTOR',
      phone: '+91 98390 44521',
      avatarUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-doc-3',
      email: 'priya.mehrotra@medilink.com',
      passwordHash: passwordDoctor,
      name: 'Dr. Priya Mehrotra, MD (Endo)',
      role: 'DOCTOR',
      phone: '+91 97210 88200',
      avatarUrl: 'https://images.unsplash.com/photo-1594824813524-1188fb8556f2?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-clinic-1',
      email: 'clinic@medilink.com',
      passwordHash: passwordClinic,
      name: 'Awadh Mediplex & Heart Institute',
      role: 'CLINIC',
      phone: '+91 522 409 1200',
      avatarUrl: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-lab-1',
      email: 'lab@medilink.com',
      passwordHash: passwordLab,
      name: 'Awadh Diagnostics & Pathology Labs',
      role: 'LABORATORY',
      phone: '+91 522 409 8899',
      avatarUrl: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'usr-lab-2',
      email: 'shubham@medilink.com',
      passwordHash: passwordLab,
      name: 'Shubham Advanced Imaging & Diagnostics',
      role: 'LABORATORY',
      phone: '+91 522 261 4411',
      avatarUrl: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=200&q=80',
      status: 'VERIFIED',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const patientProfiles: PatientProfile[] = [
    {
      id: 'pat-prof-1',
      userId: 'usr-pat-1',
      dob: '1990-08-15',
      gender: 'Male',
      bloodGroup: 'B+',
      allergies: 'Penicillin, Dust Mites',
      emergencyContact: 'Pooja Sharma (+91 98765 43211)',
      address: 'Flat 402, Gomti Heights, Vibhuti Khand, Gomti Nagar, Lucknow, UP - 226010',
      medicalHistoryJson: JSON.stringify([
        { condition: 'Mild Essential Hypertension', diagnosedYear: 2022, status: 'Managed' },
        { condition: 'Elevated Triglycerides & Dyslipidemia', diagnosedYear: 2024, status: 'Active' }
      ]),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinics: Clinic[] = [
    {
      id: 'cln-1',
      userId: 'usr-clinic-1',
      name: 'Awadh Mediplex & Heart Institute',
      address: 'TCG 4/4, Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      phone: '+91 522 409 1200',
      email: 'admin@awadhmediplex.com',
      registrationNo: 'UP-LKO-CLINIC-2022-901',
      servicesJson: JSON.stringify(['Interventional Cardiology', 'Digital ECG & 2D Echo', 'Diabetic Care Unit', 'Executive Health Checkups', 'In-house Pharmacy']),
      facilitiesJson: JSON.stringify(['Wheelchair Accessible', 'Emergency Triage', 'NABL Blood Draw Lounge', 'Covered Parking', 'Live Token Screens']),
      openingTime: '08:00',
      closingTime: '21:00',
      isVerified: true,
      rating: 4.9,
      reviewCount: 248,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-2',
      userId: 'usr-clinic-1',
      name: 'Hazratganj Superspecialty Clinic',
      address: '24 Ashok Marg, Near Hazratganj Crossing',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      phone: '+91 522 228 3344',
      email: 'hazratganj@awadhmediplex.com',
      registrationNo: 'UP-LKO-CLINIC-2021-412',
      servicesJson: JSON.stringify(['Neurosurgery & Neurology', 'Headache & Migraine Clinic', 'Spine Assessment', 'EEG & EMG Testing']),
      facilitiesJson: JSON.stringify(['Central Air Conditioning', 'Neuro Rehab Suite', 'Express Lab Counter', 'Valet Parking']),
      openingTime: '09:00',
      closingTime: '20:00',
      isVerified: true,
      rating: 4.8,
      reviewCount: 182,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cln-3',
      userId: 'usr-clinic-1',
      name: 'Kapoorthala Health & Diabetes Care Centre',
      address: 'Plot 18, Sector B, Kapoorthala, Aliganj',
      city: 'Lucknow',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8920,
      longitude: 80.9385,
      phone: '+91 522 237 9900',
      email: 'aliganj@awadhmediplex.com',
      registrationNo: 'UP-LKO-CLINIC-2023-118',
      servicesJson: JSON.stringify(['Endocrinology & Thyroid Care', 'Continuous Glucose Monitoring (CGM)', 'Diet & Lifestyle Counseling', 'Diabetic Foot Care']),
      facilitiesJson: JSON.stringify(['Consultation Chambers', 'Pharmacy', 'Diagnostic Collection Point', 'Patient Education Kiosk']),
      openingTime: '08:30',
      closingTime: '19:30',
      isVerified: true,
      rating: 4.9,
      reviewCount: 145,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const doctorProfiles: DoctorProfile[] = [
    {
      id: 'doc-prof-1',
      userId: 'usr-doc-1',
      specialty: 'Cardiology',
      subSpecialty: 'Interventional & Preventive Cardiology',
      experienceYears: 16,
      qualification: 'MBBS (KGMU Lucknow), MD (Medicine), DM (Cardiology)',
      licenseNumber: 'UPMC-54210',
      consultationFee: 800.0,
      bio: 'Senior Interventional Cardiologist in Lucknow with over 16 years of clinical excellence. Specializes in preventive cardiology, hypertension control, complex dyslipidemia management, and non-invasive cardiac evaluation.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 186,
      clinicId: 'cln-1',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-2',
      userId: 'usr-doc-2',
      specialty: 'Neurology',
      subSpecialty: 'Stroke Prevention, Headache & Neurovascular Disorders',
      experienceYears: 14,
      qualification: 'MBBS, MS (General Surgery), MCh (Neurosurgery)',
      licenseNumber: 'UPMC-48901',
      consultationFee: 1000.0,
      bio: 'Renowned Neurologist and Neurovascular specialist based at Hazratganj, Lucknow. Dedicated to migraine management, post-stroke recovery, neuropathy diagnosis, and epilepsy therapy.',
      consultationDuration: 20,
      rating: 4.8,
      reviewCount: 134,
      clinicId: 'cln-2',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      isVerified: true,
      availabilityJson: JSON.stringify(['Monday', 'Wednesday', 'Thursday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'doc-prof-3',
      userId: 'usr-doc-3',
      specialty: 'Endocrinology',
      subSpecialty: 'Type 1 & 2 Diabetes, Thyroid & Metabolic Disorders',
      experienceYears: 11,
      qualification: 'MBBS, MD (Medicine), Fellowship in Clinical Endocrinology',
      licenseNumber: 'UPMC-61204',
      consultationFee: 700.0,
      bio: 'Expert endocrinologist at Aliganj, Lucknow specializing in insulin pump titration, gestational diabetes, Hashimoto thyroiditis, and obesity-linked metabolic syndrome.',
      consultationDuration: 15,
      rating: 4.9,
      reviewCount: 112,
      clinicId: 'cln-3',
      area: 'Aliganj & Kapoorthala',
      latitude: 26.8920,
      longitude: 80.9385,
      isVerified: true,
      availabilityJson: JSON.stringify(['Tuesday', 'Wednesday', 'Friday', 'Saturday']),
      createdAt: now,
      updatedAt: now,
    }
  ];

  const clinicDoctors: ClinicDoctor[] = [
    {
      id: 'cln-doc-1',
      clinicId: 'cln-1',
      doctorId: 'doc-prof-1',
      daysAvailableJson: JSON.stringify(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']),
      roomNo: 'Chamber 101 - Cardiology OPD',
      status: 'ACTIVE',
      createdAt: now,
    },
    {
      id: 'cln-doc-2',
      clinicId: 'cln-2',
      doctorId: 'doc-prof-2',
      daysAvailableJson: JSON.stringify(['Monday', 'Wednesday', 'Thursday', 'Saturday']),
      roomNo: 'Chamber 204 - Neuro Wing',
      status: 'ACTIVE',
      createdAt: now,
    },
    {
      id: 'cln-doc-3',
      clinicId: 'cln-3',
      doctorId: 'doc-prof-3',
      daysAvailableJson: JSON.stringify(['Tuesday', 'Wednesday', 'Friday', 'Saturday']),
      roomNo: 'Chamber 108 - Endocrine Suite',
      status: 'ACTIVE',
      createdAt: now,
    }
  ];

  const laboratories: Laboratory[] = [
    {
      id: 'lab-1',
      userId: 'usr-lab-1',
      name: 'Awadh Diagnostics & Pathology Labs',
      address: 'TCG 3/3, Vibhuti Khand, Gomti Nagar',
      city: 'Lucknow',
      area: 'Gomti Nagar & Vibhuti Khand',
      latitude: 26.8500,
      longitude: 80.9990,
      phone: '+91 522 409 8899',
      email: 'reports@awadhdiagnostics.com',
      licenseNo: 'NABL-UP-MC-2022-881',
      accreditation: 'NABL Accredited & ICMR Approved Reference Lab',
      isVerified: true,
      rating: 4.9,
      reviewCount: 380,
      turnaroundTimeNote: 'Same-day 6-12 hours for routine blood panels',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'lab-2',
      userId: 'usr-lab-2',
      name: 'Shubham Advanced Imaging & Diagnostics',
      address: '12 Mahatma Gandhi Marg, Near Mayfair, Hazratganj',
      city: 'Lucknow',
      area: 'Hazratganj & Central Lucknow',
      latitude: 26.8467,
      longitude: 80.9462,
      phone: '+91 522 261 4411',
      email: 'care@shubhamdiagnostics.com',
      licenseNo: 'NABL-UP-MC-2020-410',
      accreditation: 'NABL & NABH Certified Multi-Specialty Pathology',
      isVerified: true,
      rating: 4.8,
      reviewCount: 295,
      turnaroundTimeNote: '12-24 hours guaranteed digital reports',
      homeCollectionAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const diagnosticTests: DiagnosticTest[] = [
    {
      id: 'test-1',
      labId: 'lab-1',
      name: 'Comprehensive Lipid Profile with Cardiac Risk Ratio',
      code: 'LKO-LPD-01',
      category: 'Cardiology & Lipidology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 650.0,
      discountPrice: 499.0,
      preparationInstructions: 'Fasting of 10 to 12 hours is mandatory. Water is permitted.',
      description: 'Measures Total Cholesterol, Direct HDL, Calculated LDL, Triglycerides, VLDL, and Total/HDL Chol Ratio. Essential for heart disease prevention.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol (Direct)', unit: 'mg/dL', normalRange: '> 40 (M), > 50 (F)' },
        { name: 'LDL Cholesterol', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' },
        { name: 'Total Cholesterol / HDL Ratio', unit: 'Ratio', normalRange: '3.0 - 5.0' },
        { name: 'hs-CRP (Cardiac Inflammation)', unit: 'mg/L', normalRange: '< 1.0 (Low Risk)' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-2',
      labId: 'lab-2',
      name: 'Standard Lipid Profile Screening',
      code: 'LKO-LPD-02',
      category: 'Cardiology & Lipidology',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 12,
      price: 500.0,
      discountPrice: 399.0,
      preparationInstructions: 'Strict 10-12 hour fasting required prior to blood draw.',
      description: 'Standard lipid profile test measuring cardiovascular risk factors at Hazratganj central lab.',
      parametersJson: JSON.stringify([
        { name: 'Total Cholesterol', unit: 'mg/dL', normalRange: '125 - 200' },
        { name: 'HDL Cholesterol', unit: 'mg/dL', normalRange: '> 40' },
        { name: 'LDL Cholesterol', unit: 'mg/dL', normalRange: '< 100' },
        { name: 'Triglycerides', unit: 'mg/dL', normalRange: '< 150' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-3',
      labId: 'lab-1',
      name: 'Comprehensive Metabolic & Renal Function Panel (KFT + LFT)',
      code: 'LKO-KFT-LFT-01',
      category: 'Biochemistry & Renal/Hepatic',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 8,
      price: 850.0,
      discountPrice: 650.0,
      preparationInstructions: 'Fasting 8-10 hours recommended.',
      description: 'Complete biochemical assessment evaluating kidney parameters (Urea, Creatinine, Uric Acid, eGFR) and liver enzymes (Bilirubin, SGOT, SGPT, Alkaline Phosphatase).',
      parametersJson: JSON.stringify([
        { name: 'Fasting Plasma Glucose', unit: 'mg/dL', normalRange: '70 - 99' },
        { name: 'Blood Urea', unit: 'mg/dL', normalRange: '15 - 40' },
        { name: 'Serum Creatinine', unit: 'mg/dL', normalRange: '0.6 - 1.2' },
        { name: 'Serum Uric Acid', unit: 'mg/dL', normalRange: '3.5 - 7.2' },
        { name: 'Total Bilirubin', unit: 'mg/dL', normalRange: '0.2 - 1.2' },
        { name: 'SGPT (ALT)', unit: 'U/L', normalRange: '0 - 45' },
        { name: 'SGOT (AST)', unit: 'U/L', normalRange: '0 - 40' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-4',
      labId: 'lab-1',
      name: 'HbA1c Glycated Hemoglobin with Average Estimated Glucose',
      code: 'LKO-GLY-A1C',
      category: 'Endocrinology & Diabetes',
      sampleType: 'Whole Blood EDTA',
      turnaroundHours: 6,
      price: 550.0,
      discountPrice: 399.0,
      preparationInstructions: 'No fasting required. Sample can be collected at any time.',
      description: 'Gold standard automated HPLC test reflecting 3-month blood sugar control for diabetic monitoring.',
      parametersJson: JSON.stringify([
        { name: 'HbA1c', unit: '%', normalRange: '< 5.7 (Normal), 5.7 - 6.4 (Prediabetes)' },
        { name: 'Estimated Average Glucose (eAG)', unit: 'mg/dL', normalRange: '90 - 120' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-5',
      labId: 'lab-2',
      name: 'Thyroid Function Profile Total (T3, T4, TSH Ultra-Sensitive)',
      code: 'LKO-THY-TOT',
      category: 'Endocrinology & Thyroid',
      sampleType: 'Serum (Venous Blood)',
      turnaroundHours: 12,
      price: 600.0,
      discountPrice: 450.0,
      preparationInstructions: 'Morning collection advised. Do not take thyroid medication until after sample collection.',
      description: 'Evaluates hyperthyroidism and hypothyroidism functionality using ultra-sensitive chemiluminescence assay.',
      parametersJson: JSON.stringify([
        { name: 'TSH (Ultrasensitive)', unit: 'uIU/mL', normalRange: '0.35 - 4.94' },
        { name: 'Total T3 (Triiodothyronine)', unit: 'ng/dL', normalRange: '80 - 200' },
        { name: 'Total T4 (Thyroxine)', unit: 'ug/dL', normalRange: '5.1 - 14.1' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'test-6',
      labId: 'lab-1',
      name: 'Complete Blood Count (CBC) with ESR & Automated Smear',
      code: 'LKO-CBC-ESR',
      category: 'Hematology',
      sampleType: 'Whole Blood EDTA',
      turnaroundHours: 4,
      price: 400.0,
      discountPrice: 299.0,
      preparationInstructions: 'No special preparation needed. Fasting not required.',
      description: '28-parameter automated hemogram evaluating anemia, infections, platelet counts, and inflammatory ESR.',
      parametersJson: JSON.stringify([
        { name: 'Hemoglobin', unit: 'g/dL', normalRange: '13.0 - 17.0 (M), 12.0 - 15.0 (F)' },
        { name: 'Total Leukocyte Count (TLC)', unit: '/cumm', normalRange: '4,000 - 11,000' },
        { name: 'Platelet Count', unit: 'lakh/cumm', normalRange: '1.5 - 4.5' },
        { name: 'ESR (Westergren)', unit: 'mm/1st hr', normalRange: '0 - 15' }
      ]),
      isAvailable: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const appointments: Appointment[] = [
    {
      id: 'apt-1',
      appointmentNumber: 'LKO-APT-2026-101',
      patientId: 'pat-prof-1',
      doctorId: 'doc-prof-1',
      clinicId: 'cln-1',
      date: todayStr,
      timeSlot: '09:30 AM',
      type: 'IN_PERSON',
      status: 'CONFIRMED',
      symptoms: 'Mild chest tightness upon morning brisk walking and follow-up on lipid profile.',
      notes: 'Patient advised to bring previous reports from Awadh Diagnostics.',
      feePaid: 800.0,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'apt-2',
      appointmentNumber: 'LKO-APT-2026-102',
      patientId: 'pat-prof-1',
      doctorId: 'doc-prof-3',
      clinicId: 'cln-3',
      date: '2026-10-10',
      timeSlot: '11:00 AM',
      type: 'TELECONSULT',
      status: 'CONFIRMED',
      symptoms: 'Quarterly review of metabolic markers & personalized diabetic nutrition.',
      notes: 'Telehealth link will be enabled 15 minutes before the session.',
      feePaid: 700.0,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const queues: Queue[] = [
    {
      id: 'que-1',
      doctorId: 'doc-prof-1',
      clinicId: 'cln-1',
      date: todayStr,
      currentTokenNumber: 3,
      status: 'ACTIVE',
      averageConsultationMin: 15,
      delayMinutes: 5,
      updatedAt: now,
    }
  ];

  const queueTickets: QueueTicket[] = [
    {
      id: 'qtk-1',
      queueId: 'que-1',
      appointmentId: 'apt-1',
      patientId: 'pat-prof-1',
      tokenNumber: 4,
      estimatedTime: '10:15 AM',
      status: 'WAITING',
      checkInTime: now,
    },
    {
      id: 'qtk-prev-1',
      queueId: 'que-1',
      appointmentId: 'apt-mock-1',
      patientId: 'pat-mock-1',
      tokenNumber: 1,
      estimatedTime: '09:00 AM',
      status: 'COMPLETED',
      checkInTime: now,
      calledTime: now,
      completedTime: now,
    },
    {
      id: 'qtk-prev-2',
      queueId: 'que-1',
      appointmentId: 'apt-mock-2',
      patientId: 'pat-mock-2',
      tokenNumber: 2,
      estimatedTime: '09:20 AM',
      status: 'COMPLETED',
      checkInTime: now,
      calledTime: now,
      completedTime: now,
    },
    {
      id: 'qtk-current-3',
      queueId: 'que-1',
      appointmentId: 'apt-mock-3',
      patientId: 'pat-mock-3',
      tokenNumber: 3,
      estimatedTime: '09:45 AM',
      status: 'IN_CONSULTATION',
      checkInTime: now,
      calledTime: now,
    }
  ];

  const referrals: Referral[] = [
    {
      id: 'ref-1',
      referralCode: 'REF-LKO-CARD-081',
      doctorId: 'doc-prof-1',
      patientId: 'pat-prof-1',
      labId: 'lab-1',
      testId: 'test-1',
      notes: 'Advised Comprehensive Lipid Profile with hs-CRP prior to dosage titration.',
      priority: 'NORMAL',
      status: 'BOOKED',
      createdAt: now,
      updatedAt: now,
    }
  ];

  const testBookings: TestBooking[] = [
    {
      id: 'tb-1',
      bookingNumber: 'LKO-TB-2026-401',
      patientId: 'pat-prof-1',
      labId: 'lab-1',
      testId: 'test-1',
      referralId: 'ref-1',
      collectionType: 'WALK_IN',
      scheduledDate: todayStr,
      scheduledTimeSlot: '08:30 AM',
      collectionAddress: 'TCG 3/3, Vibhuti Khand, Gomti Nagar, Lucknow, UP',
      status: 'SAMPLE_COLLECTED',
      totalAmount: 499.0,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const samples: Sample[] = [
    {
      id: 'smp-1',
      testBookingId: 'tb-1',
      barcode: 'SMP-LKO-90812-AD',
      sampleType: 'Venous Blood (Serum SST Vacutainer)',
      collectedAt: now,
      collectedBy: 'P. Verma, Senior Phlebotomist (Awadh Labs)',
      status: 'ANALYZING',
      temperature: '4°C Controlled Cold-Chain',
      updatedAt: now,
    }
  ];

  const medicalReports: MedicalReport[] = [
    {
      id: 'rep-1',
      testBookingId: 'tb-1',
      patientId: 'pat-prof-1',
      labId: 'lab-1',
      doctorId: 'doc-prof-1',
      reportTitle: 'Comprehensive Lipid Profile with Cardiac Risk Ratio',
      testCategory: 'Cardiology',
      fileUrl: '/uploads/sample_cardiac_lipid_report.pdf',
      fileName: 'Awadh_Lipid_Cardio_Report_RSharma_2026.pdf',
      fileSize: 245800,
      mimeType: 'application/pdf',
      summary: 'Total Cholesterol (238 mg/dL) and LDL-C (154 mg/dL) are elevated above standard optimal boundaries. High-sensitivity CRP (2.8 mg/L) indicates moderate vascular inflammation. Protective HDL remains within healthy limits.',
      extractedFactsJson: JSON.stringify([
        { parameter: 'Total Cholesterol', value: '238', unit: 'mg/dL', referenceRange: '125 - 200', flag: 'HIGH' },
        { parameter: 'HDL Cholesterol (Direct)', value: '54', unit: 'mg/dL', referenceRange: '> 40', flag: 'NORMAL' },
        { parameter: 'LDL Cholesterol', value: '154', unit: 'mg/dL', referenceRange: '< 100', flag: 'HIGH' },
        { parameter: 'Triglycerides', value: '152', unit: 'mg/dL', referenceRange: '< 150', flag: 'BORDERLINE HIGH' },
        { parameter: 'hs-CRP (Cardiac Risk)', value: '2.8', unit: 'mg/L', referenceRange: '< 1.0', flag: 'HIGH' }
      ]),
      aiAnalysisJson: JSON.stringify({
        summary: 'The laboratory report from Awadh Diagnostics reveals elevated LDL cholesterol at 154 mg/dL along with elevated hs-CRP at 2.8 mg/L. HDL protective cholesterol is at a healthy 54 mg/dL.',
        abnormalFindings: [
          'LDL Cholesterol of 154 mg/dL exceeds normal reference range (<100 mg/dL).',
          'hs-CRP of 2.8 mg/L indicates moderate chronic vascular inflammation.',
          'Triglycerides slightly above optimal threshold (152 mg/dL vs <150 mg/dL).'
        ],
        possibleGeneralMeanings: 'Elevated LDL combined with higher hs-CRP is often associated with cardiovascular risk in South Asian populations. These markers frequently warrant clinical assessment regarding lifestyle, dietary adjustments, and possible lipid-lowering medical management.',
        relevantSpecialties: ['Cardiology', 'Internal Medicine', 'Preventive Health'],
        suggestedQuestionsForDoctor: [
          'What is my cardiovascular risk score based on these numbers?',
          'Should I begin or modify medication (e.g. statin therapy) or start with targeted dietary and exercise adjustments?',
          'How frequently should my lipid profile and hs-CRP be rechecked?'
        ],
        disclaimer: 'AI-generated information is for educational and healthcare-navigation purposes only. It is not a diagnosis or a substitute for professional medical advice.'
      }),
      status: 'PUBLISHED',
      publishedAt: now,
      isSharedWithDoctor: true,
      createdAt: now,
      updatedAt: now,
    }
  ];

  const reviews: Review[] = [
    {
      id: 'rev-1',
      patientId: 'pat-prof-1',
      targetType: 'DOCTOR',
      targetId: 'doc-prof-1',
      rating: 5,
      comment: 'Dr. Ananya Srivastava explained every aspect of my lipid report patiently. The live OPD queue token made the visit completely stress-free with zero waiting at Awadh Mediplex!',
      isVerifiedVisit: true,
      createdAt: now,
    },
    {
      id: 'rev-2',
      patientId: 'pat-prof-1',
      targetType: 'LABORATORY',
      targetId: 'lab-1',
      rating: 5,
      comment: 'Prompt home phlebotomy collection in Gomti Nagar. The sample was drawn safely and the verified digital report was ready within 6 hours.',
      isVerifiedVisit: true,
      createdAt: now,
    }
  ];

  const notifications: Notification[] = [
    {
      id: 'notif-1',
      userId: 'usr-pat-1',
      title: 'Appointment Confirmed',
      message: 'Your cardiology consultation with Dr. Ananya Srivastava is confirmed for today at 09:30 AM at Awadh Mediplex, Gomti Nagar.',
      type: 'APPOINTMENT',
      link: '/patient/appointments',
      isRead: false,
      createdAt: now,
    },
    {
      id: 'notif-2',
      userId: 'usr-pat-1',
      title: 'Live OPD Queue Token #4',
      message: 'Token #4 is assigned for Dr. Ananya Srivastava. Estimated call time: 10:15 AM.',
      type: 'QUEUE',
      link: '/patient/appointments',
      isRead: false,
      createdAt: now,
    },
    {
      id: 'notif-3',
      userId: 'usr-pat-1',
      title: 'Diagnostic Sample Under Automated Analysis',
      message: 'Sample Barcode SMP-LKO-90812-AD received at Awadh Diagnostics (Vibhuti Khand) and is undergoing automated testing.',
      type: 'SAMPLE',
      link: '/patient/lab-bookings',
      isRead: false,
      createdAt: now,
    },
    {
      id: 'notif-4',
      userId: 'usr-doc-1',
      title: 'Live OPD Queue Active',
      message: 'Today\'s clinical queue is live with 4 scheduled patients at Chamber 101, Awadh Mediplex.',
      type: 'QUEUE',
      link: '/doctor/queue',
      isRead: false,
      createdAt: now,
    }
  ];

  const auditLogs: AuditLog[] = [
    {
      id: 'aud-1',
      userId: 'usr-admin-1',
      action: 'SYSTEM_BOOTSTRAP',
      resourceType: 'PLATFORM',
      resourceId: 'MEDILINK-LUCKNOW-CORE',
      ipAddress: '127.0.0.1',
      userAgent: 'Server-Init/1.0',
      detailsJson: JSON.stringify({ message: 'MediLink Lucknow Healthcare Ecosystem initialized with verified Indian medical entities.' }),
      createdAt: now,
    }
  ];

  return {
    users,
    patientProfiles,
    doctorProfiles,
    clinics,
    clinicDoctors,
    laboratories,
    diagnosticTests,
    appointments,
    queues,
    queueTickets,
    referrals,
    testBookings,
    samples,
    medicalReports,
    reviews,
    notifications,
    auditLogs
  };
}
